/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package usuarioPresentacion;

import CajaDeAhorro.bd.domain.Rol;
import CajaDeAhorro.bd.domain.Usuario;
import CajaDeAhorro.dao.rol.RolDaoImpl;
import CajaDeAhorro.dao.usuario.UsuarioDaoImpl;
import loginPresentacion.LoginPresentacion;
import java.awt.Image;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import loginPresentacion.VentanaAdministradorPresentacion;

/**
 *
 * @author Jonatan Eduardo
 */
public class ConfiguracionUsuario extends javax.swing.JFrame {

    Map<String, Integer> MapitaRoles = new HashMap<>();  //variable global
    String rolSeleccionado = "Seleccione una opción";
    String tipoBusqueda = "ID Usuario";

    /**
     * Creates new form ConfiguracionUsuario
     */
    public ConfiguracionUsuario() {
        initComponents();
        setTitle("Panel de control de Usuarios"); // Añade un título a la ventana
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        setResizable(false); // Hace que el tamaño de la ventana sea fijo
        SetImageLabel(imgbuscar, "src/main/java/Img/lupa.png");//para autopajustar laimagen al labael
        cargarListaUsuarios();
        cargarRoles();
        txtIdUsuario.setEditable(false);
    }

    public void cargarListaUsuarios() {
        UsuarioDaoImpl enlace = new UsuarioDaoImpl();
        java.util.List<Usuario> listaDeUsuarios = enlace.obtenerTodosLosUsuarios();

        DefaultTableModel modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("ID Usuario");
        modeloTabla.addColumn("ID Rol");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Correo");
        modeloTabla.addColumn("Contraseña");

        for (Usuario usuario : listaDeUsuarios) {
            modeloTabla.addRow(new Object[]{usuario.getIdUsuario(), usuario.getIdRol(), usuario.getNombre(), usuario.getCorreo(), usuario.getContraseña()});
        }
        tablaUsuarios.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        imgbuscar = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        txtContraseña = new javax.swing.JTextField();
        txtIdUsuario = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ComboxRoles = new javax.swing.JComboBox<>();
        btnEliminar1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        filtro = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(991, 564));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 560, 30));
        jPanel1.add(imgbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 30, 30));

        btnRegresar.setBackground(new java.awt.Color(131, 46, 5));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("REGRESAR");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 40));

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Usuario", "ID Rol", "Nombre", "Correo", "Contraseña"
            }
        ));
        tablaUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaUsuarios.setSelectionBackground(new java.awt.Color(153, 51, 0));
        tablaUsuarios.getTableHeader().setResizingAllowed(false);
        tablaUsuarios.getTableHeader().setReorderingAllowed(false);
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 560, 260));
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, 270, -1));

        txtIdUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtIdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 270, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 270, -1));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 270, -1));

        btnNuevo.setBackground(new java.awt.Color(131, 46, 5));
        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("AGREGAR NUEVO");
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 170, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID Usuario:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rol del Usuario:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Correo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(131, 46, 5));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 100, 40));

        btnEliminar.setBackground(new java.awt.Color(131, 46, 5));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 460, 120, 40));

        btnActualizar.setBackground(new java.awt.Color(131, 46, 5));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 120, 40));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 1, 28)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PANEL DE CONTROL DE USUARIOS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 520, 40));

        ComboxRoles.setBackground(new java.awt.Color(153, 51, 0));
        ComboxRoles.setForeground(new java.awt.Color(255, 255, 255));
        ComboxRoles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboxRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboxRolesActionPerformed(evt);
            }
        });
        jPanel1.add(ComboxRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 270, 30));

        btnEliminar1.setBackground(new java.awt.Color(7, 58, 33));
        btnEliminar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar1.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar1.setText("LIstar todos los usuarios");
        btnEliminar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 560, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Seleccione:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        filtro.setBackground(new java.awt.Color(153, 51, 0));
        filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Usuario", "Nombre" }));
        filtro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filtro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filtroMouseClicked(evt);
            }
        });
        filtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroActionPerformed(evt);
            }
        });
        jPanel1.add(filtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jonatan Eduardo\\Documents\\GitHub\\Caja-De-Ahorro\\CajaDeAhorroPresentacion\\src\\main\\java\\Img\\fondo2.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VentanaAdministradorPresentacion abrir = new VentanaAdministradorPresentacion();
        abrir.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        InsertarUsuario abrir = new InsertarUsuario();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (txtIdUsuario.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Seleccione un elemento de la tabla", "Error al eliminar", JOptionPane.ERROR_MESSAGE);
        } else {
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar este Usuario?", "Eliminar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (confirmacion == JOptionPane.YES_OPTION) {
                Usuario usuarioEliminado = new Usuario();
                // Usuario ha seleccionado "Sí" (Eliminar)
                UsuarioDaoImpl enlace = new UsuarioDaoImpl();
                usuarioEliminado = enlace.eliminarUsuario(Integer.parseInt(txtIdUsuario.getText()));
                JOptionPane.showMessageDialog(this, "Rol eliminado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                cargarListaUsuarios();
                cargarRoles();
                limpiar();

            } else {
                // Usuario ha seleccionado "No" (Cancelar)
                System.out.println("El usuario ha cancelado la eliminación del rol.");
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        if (txtIdUsuario.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Seleccione un elemento de la tabla", "Error al actualizar", JOptionPane.ERROR_MESSAGE);
        } else {
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Está seguro de querer actualizar este usuario?", "Actualizar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (confirmacion == JOptionPane.YES_OPTION) {
                Usuario nuevoUsuario = new Usuario();
                int IdRol= MapitaRoles.get(rolSeleccionado);
                if(IdRol==-1){
                    JOptionPane.showMessageDialog(this, "Seleccione un rol para el usuario", "Error al actualizar", JOptionPane.ERROR_MESSAGE);
                }else
                {
                   nuevoUsuario.setIdRol(IdRol);
                   nuevoUsuario.setCorreo(txtCorreo.getText());
                   nuevoUsuario.setNombre(txtNombre.getText());
                   nuevoUsuario.setContraseña(txtContraseña.getText());
                   UsuarioDaoImpl enlace =  new UsuarioDaoImpl();
                   enlace.actualizarUsuario(Integer.parseInt(txtIdUsuario.getText()), nuevoUsuario);
                   JOptionPane.showMessageDialog(this, "Usuarop actualizado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                   limpiar();
                   cargarRoles();
                   cargarListaUsuarios();
                }
            } else {
                // Usuario ha seleccionado "No" (Cancelar)
                System.out.println("El usuario ha cancelado la actualizacion del rol.");
            }
        

    }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        // TODO add your handling code here:
        // Obtener el índice de la fila seleccionada
        int filaSeleccionada = tablaUsuarios.getSelectedRow();

        // Verificar que la fila seleccionada sea válida
        if (filaSeleccionada != -1) {
            // Obtener los valores de las celdas de la fila seleccionada
            Object idUsuario = tablaUsuarios.getValueAt(filaSeleccionada, 0);
            Object idRol = tablaUsuarios.getValueAt(filaSeleccionada, 1);
            Object nombre = tablaUsuarios.getValueAt(filaSeleccionada, 2);
            Object correo = tablaUsuarios.getValueAt(filaSeleccionada, 3);
            Object contraseña = tablaUsuarios.getValueAt(filaSeleccionada, 4);

            // Buscar el nombre del rol utilizando el Map
            String nombreRol = "";
            for (Map.Entry<String, Integer> entry : MapitaRoles.entrySet()) {
                if (entry.getValue() == idRol) {
                    nombreRol = entry.getKey();
                    break; // Terminar el bucle una vez encontrado el nombre del rol
                }
            }

            // Iterar sobre las opciones del JComboBox para encontrar el índice del elemento
            for (int i = 0; i < ComboxRoles.getItemCount(); i++) {
                String item = (String) ComboxRoles.getItemAt(i); // Obtener el elemento en la posición i
                if (item.equals(nombreRol)) {
                    ComboxRoles.setSelectedIndex(i); // Establecer el elemento seleccionado en el JComboBox
                    break; // Terminar el bucle una vez encontrado el elemento
                }
            }

            // Mostrar los valores en los JTextField correspondientes
            txtIdUsuario.setText(idUsuario.toString());
            txtNombre.setText(nombre.toString());
            txtCorreo.setText(correo.toString());
            txtContraseña.setText(contraseña.toString());
        }
    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void ComboxRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboxRolesActionPerformed
        // TODO add your handling code here:
        rolSeleccionado = (String) ComboxRoles.getModel().getSelectedItem();
    }//GEN-LAST:event_ComboxRolesActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        tablaUsuarios.removeAll();
        cargarListaUsuarios();
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void filtroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filtroMouseClicked

    }//GEN-LAST:event_filtroMouseClicked

    private void filtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroActionPerformed
        // TODO add your handling code here:
        tipoBusqueda = (String) filtro.getSelectedItem();
        System.out.println(tipoBusqueda);
    }//GEN-LAST:event_filtroActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        UsuarioDaoImpl enlace = new UsuarioDaoImpl();
        DefaultTableModel modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("ID Usuario");
        modeloTabla.addColumn("ID Rol");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Correo");
        modeloTabla.addColumn("Contraseña");
        if (tipoBusqueda.equalsIgnoreCase("Nombre")) {
            java.util.List<Usuario> listaDeUsuarios = enlace.obtenerUsuarioPorNombre(txtBuscar.getText());
            for (Usuario usuario : listaDeUsuarios) {
                modeloTabla.addRow(new Object[]{usuario.getIdUsuario(), usuario.getIdRol(), usuario.getNombre(), usuario.getCorreo(), usuario.getContraseña()});
            }
            tablaUsuarios.setModel(modeloTabla);
        }
        if (tipoBusqueda.equalsIgnoreCase("ID Usuario")) {
            if (txtBuscar.getText().isEmpty() || !txtBuscar.getText().matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "El campo de búsqueda no puede estar vacío y solo se permiten numeros enteros", "Error al buscar", JOptionPane.ERROR_MESSAGE);
            } else {
                Usuario UsuarioEncontrado = enlace.obtenerUsuarioPorId(Integer.parseInt(txtBuscar.getText()));
                if (UsuarioEncontrado != null) {
                    modeloTabla.addRow(new Object[]{UsuarioEncontrado.getIdUsuario(), UsuarioEncontrado.getIdRol(), UsuarioEncontrado.getNombre(), UsuarioEncontrado.getCorreo(), UsuarioEncontrado.getContraseña()});
                    tablaUsuarios.setModel(modeloTabla);
                }else
                {
                    System.out.println("Hay que limpiar la tabla");
                    modeloTabla.addRow(new Object[]{"", "", ""});
                    tablaUsuarios.setModel(modeloTabla);
                }

            }

        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtIdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionUsuario.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionUsuario.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionUsuario.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionUsuario.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfiguracionUsuario().setVisible(true);
            }
        });
    }

    private void SetImageLabel(JLabel Nombrelabel, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(Nombrelabel.getWidth(), Nombrelabel.getHeight(), Image.SCALE_DEFAULT));
        Nombrelabel.setIcon(icon);
        this.repaint();
    }

    public void cargarRoles() {
        RolDaoImpl rolBaseDatos = new RolDaoImpl();
        java.util.List<Rol> listaDeRoles = rolBaseDatos.obtenerTodosLosRoles();

        // Crear un modelo para el combo box
        DefaultComboBoxModel<String> modeloComboRoles = new DefaultComboBoxModel<>();

        //Limpiamos el mapa
        MapitaRoles.clear();

        //Inicializamos la primer opcion del combobox
        modeloComboRoles.addElement("Seleccione una opción");//añadimos al comnbobox
        MapitaRoles.put("Seleccione una opción", -1);

        //Iteramos sobre la lista de roles
        for (Rol rol : listaDeRoles) {
            modeloComboRoles.addElement(rol.getNombre());//añadimos al comnbobox
            MapitaRoles.put(rol.getNombre(), rol.getIdRol());//añadimos a nuestro mapa
        }
        ComboxRoles.setModel(modeloComboRoles);
    }

    public void limpiar() {
        txtIdUsuario.setText("");
        txtNombre.setText("");
        txtCorreo.setText("");
        txtContraseña.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboxRoles;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> filtro;
    private javax.swing.JLabel imgbuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
