/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package estadoPrestamoPresentacion;

import CajaDeAhorro.bd.domain.Pago;
import CajaDeAhorro.dao.pago.PagoDaoImpl;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import loginPresentacion.VentanaAdministradorPresentacion;

/**
 *
 * @author Gamem
 */
public class estadoPrestamoPresentacion extends javax.swing.JFrame {

    /**
     * Creates new form EstadoPrestamoPresentacion
     */
    public estadoPrestamoPresentacion() {
        initComponents();        
        setTitle("Panel de Estado de Prestamo"); // Añade un título a la ventana        setResizable(false); // Hace que el tamaño de la ventana sea fijo

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBuscarPrestamo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPagos = new javax.swing.JTable();
        inIdPrestamo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        btnRegresar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setSize(new java.awt.Dimension(1080, 720));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarPrestamo.setBackground(new java.awt.Color(131, 46, 5));
        btnBuscarPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarPrestamo.setText("BUSCAR");
        btnBuscarPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPrestamoActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 110, 40));

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 1, 28)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PANEL DE ESTADO DE PRESTAMO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 460, 40));

        tablaPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id pago", "id prestamo", "cantidad", "fecha"
            }
        ));
        jScrollPane1.setViewportView(tablaPagos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 750, 370));

        inIdPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inIdPrestamoActionPerformed(evt);
            }
        });
        jPanel1.add(inIdPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 260, 30));

        jTextPane1.setText("Ingresar Id del Prestamo");
        jScrollPane2.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 190, -1));

        btnRegresar2.setBackground(new java.awt.Color(131, 46, 5));
        btnRegresar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegresar2.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar2.setText("REGRESAR");
        btnRegresar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPrestamoActionPerformed
        // TODO add your handling code here:
        
        LocalDateTime fecha = LocalDateTime.now(); // Obtener la fecha y hora actual
        PagoDaoImpl enlace = new PagoDaoImpl();
        java.util.List<Pago> listaDePagos = enlace.pagosRealizadosPorSocio(Integer.valueOf( inIdPrestamo.getText()), fecha );

        DefaultTableModel modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("id pago");
        modeloTabla.addColumn("id prestamo");
        modeloTabla.addColumn("cantidad");
        modeloTabla.addColumn("fecha");

        for (Pago usuario : listaDePagos) {
            modeloTabla.addRow(new Object[]{usuario.getIdPago(), usuario.getIdPrestamo(), usuario.getCantidad(), usuario.getFecha().toString().substring(0, 10)});
        }
        tablaPagos.setModel(modeloTabla); 
        
    }//GEN-LAST:event_btnBuscarPrestamoActionPerformed

    private void inIdPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inIdPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inIdPrestamoActionPerformed

    private void btnRegresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar2ActionPerformed
        // TODO add your handling code here:
        VentanaAdministradorPresentacion abrir = new VentanaAdministradorPresentacion();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(estadoPrestamoPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(estadoPrestamoPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(estadoPrestamoPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(estadoPrestamoPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new estadoPrestamoPresentacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPrestamo;
    private javax.swing.JButton btnRegresar2;
    private javax.swing.JTextField inIdPrestamo;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTable tablaPagos;
    // End of variables declaration//GEN-END:variables
}
