/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package socioPresentacion;

import CajaDeAhorro.bd.domain.Socio;
import CajaDeAhorro.dao.Socio.SocioDaoImpl;
import javax.swing.JOptionPane;

/**
 *
 * @author Gamem
 */
public class InsertarSocio extends javax.swing.JFrame {

    /**
     * Creates new form InsertarSocio
     */
    public InsertarSocio() {
        setTitle("Panel de insertar Socios"); // Añade un título a la ventana        setResizable(false); // Hace que el tamaño de la ventana sea fijo
        initComponents();
    }

    private void LimpiarCampos() {
        inputNewNombre.setText("");
        inputNewApellidos.setText("");
        inputNewTelefono.setText("");
        inputNewDireccion.setText("");
        inputNewCorreo.setText("");    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InsertarSocio = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        botonRegresarSocio = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        inputNewNombre = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        inputNewApellidos = new javax.swing.JTextField();
        inputNewDireccion = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        inputNewTelefono = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        inputNewCorreo = new javax.swing.JTextField();
        botonInsertarSocio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 700));

        InsertarSocio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        InsertarSocio.setDoubleBuffered(false);
        InsertarSocio.setMinimumSize(new java.awt.Dimension(1000, 1000));
        InsertarSocio.setPreferredSize(new java.awt.Dimension(600, 700));
        InsertarSocio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 1, 28)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("INSERTAR NUEVO SOCIO");
        InsertarSocio.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 390, 40));

        botonRegresarSocio.setBackground(new java.awt.Color(131, 46, 5));
        botonRegresarSocio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonRegresarSocio.setForeground(new java.awt.Color(255, 255, 255));
        botonRegresarSocio.setText("REGRESAR");
        botonRegresarSocio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarSocioActionPerformed(evt);
            }
        });
        InsertarSocio.add(botonRegresarSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 40));

        jLabel19.setText("Nombre");
        InsertarSocio.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 70, 20));

        inputNewNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNewNombreActionPerformed(evt);
            }
        });
        InsertarSocio.add(inputNewNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 420, 30));

        jLabel20.setText("Apellidos");
        InsertarSocio.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 70, 20));

        inputNewApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNewApellidosActionPerformed(evt);
            }
        });
        InsertarSocio.add(inputNewApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 420, 30));

        inputNewDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNewDireccionActionPerformed(evt);
            }
        });
        InsertarSocio.add(inputNewDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 420, 30));

        jLabel21.setText("Direccion");
        InsertarSocio.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 70, 20));

        jLabel22.setText("Telefono");
        InsertarSocio.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 70, 20));

        inputNewTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNewTelefonoActionPerformed(evt);
            }
        });
        InsertarSocio.add(inputNewTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 420, 30));

        jLabel23.setText("Correo");
        InsertarSocio.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 70, 20));

        inputNewCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNewCorreoActionPerformed(evt);
            }
        });
        InsertarSocio.add(inputNewCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 420, 30));

        botonInsertarSocio.setBackground(new java.awt.Color(131, 46, 5));
        botonInsertarSocio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonInsertarSocio.setForeground(new java.awt.Color(255, 255, 255));
        botonInsertarSocio.setText("INSERTAR");
        botonInsertarSocio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonInsertarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInsertarSocioActionPerformed(evt);
            }
        });
        InsertarSocio.add(botonInsertarSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InsertarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InsertarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarSocioActionPerformed
        // TODO add your handling code here:
        socioPresentacion abrir= new socioPresentacion();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegresarSocioActionPerformed

    private void botonInsertarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInsertarSocioActionPerformed
        //verificar que no esten vacios los campos
        
        if(inputNewNombre.getText().trim().isEmpty() || inputNewCorreo.getText().trim().isEmpty() || inputNewApellidos.getText().trim().isEmpty() || inputNewDireccion.getText().trim().isEmpty() || inputNewTelefono.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Debe rellenar todos los campos y seleccionar un rol.", "Error al insertar", JOptionPane.ERROR_MESSAGE);
        }else
        {
            Socio nuevoSocio = new Socio();
            nuevoSocio.setNombre(inputNewNombre.getText());
            nuevoSocio.setCorreo(inputNewCorreo.getText());
            nuevoSocio.setTelefono(inputNewTelefono.getText());
            nuevoSocio.setDireccion(inputNewDireccion.getText());
            nuevoSocio.setApellidos(inputNewApellidos.getText());

            SocioDaoImpl conexionBd = new  SocioDaoImpl();
            conexionBd.crearSocio(nuevoSocio);
            JOptionPane.showMessageDialog(this, "Socio insertado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            LimpiarCampos();
        }
    }//GEN-LAST:event_botonInsertarSocioActionPerformed

    private void inputNewCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNewCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNewCorreoActionPerformed

    private void inputNewTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNewTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNewTelefonoActionPerformed

    private void inputNewDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNewDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNewDireccionActionPerformed

    private void inputNewApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNewApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNewApellidosActionPerformed

    private void inputNewNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNewNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNewNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarSocio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InsertarSocio;
    private javax.swing.JButton botonInsertarSocio;
    private javax.swing.JButton botonRegresarSocio;
    private javax.swing.JTextField inputNewApellidos;
    private javax.swing.JTextField inputNewCorreo;
    private javax.swing.JTextField inputNewDireccion;
    private javax.swing.JTextField inputNewNombre;
    private javax.swing.JTextField inputNewTelefono;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

}
