/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package socioPresentacion;

import CajaDeAhorro.bd.domain.Socio;
import CajaDeAhorro.dao.Socio.SocioDaoImpl;
import loginPresentacion.VentanaAdministradorPresentacion;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gamem
 */
public class socioPresentacion extends javax.swing.JFrame {

    /**
     * Creates new form cuentaPresentacion
     */
    public socioPresentacion() {
        initComponents();
        setTitle("Panel de control de Socios"); // Añade un título a la ventana
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        setResizable(false); // Hace que el tamaño de la ventana sea fijo
        cargarSocios();
    }

    public void limpiar() {
        inputIdSocio.setText("");
        inputNombre.setText("");
        inputApellidos.setText("");
        inputTelefono.setText("");
        inputDireccion.setText("");
        inputCorreo.setText("");
    }

    public void cargarSocios() {
        SocioDaoImpl enlace = new SocioDaoImpl();
        List<Socio> listaSocios = enlace.obtenerTodosLosSocios();
        DefaultTableModel modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("id_socio");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Apellidos");
        modeloTabla.addColumn("Direccion");
        modeloTabla.addColumn("Telefono");
        modeloTabla.addColumn("Correo");

        for (Socio socio : listaSocios) {
            modeloTabla.addRow(new Object[]{socio.getId_socio(), socio.getNombre(), socio.getApellidos(), socio.getDireccion(), socio.getTelefono(), socio.getCorreo()});
        }
        tablaSocios.setModel(modeloTabla);
        //tablaso.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSocios = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        inputApellidos = new javax.swing.JTextField();
        inputDireccion = new javax.swing.JTextField();
        inputTelefono = new javax.swing.JTextField();
        inputCorreo = new javax.swing.JTextField();
        botonEliminarSocio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnRegresar1 = new javax.swing.JButton();
        botonActualizarSocio = new javax.swing.JButton();
        botonEliminarSocio1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaSocios1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        inputNombre1 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        inputApellidos1 = new javax.swing.JTextField();
        inputDireccion1 = new javax.swing.JTextField();
        inputTelefono1 = new javax.swing.JTextField();
        inputCorreo1 = new javax.swing.JTextField();
        botonEliminarSocio2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnRegresar2 = new javax.swing.JButton();
        botonActualizarSocio1 = new javax.swing.JButton();
        botonEliminarSocio3 = new javax.swing.JButton();
        inputIdSocio = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(60, 63, 65));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id_socio", "Nombre", "Apellidos", "Direccion", "Telefono", "Correo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaSocios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSociosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaSocios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 570, 340));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 1, 28)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PANEL DE CONTROL DE SOCIOS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 440, 40));

        inputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreActionPerformed(evt);
            }
        });
        jPanel1.add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 420, 30));

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTextPane1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextPane1.setText("Lista de todos los socios");
        jTextPane1.setToolTipText("");
        jTextPane1.setCaretColor(new java.awt.Color(0, 0, 0));
        jScrollPane4.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 570, 40));

        inputApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputApellidosActionPerformed(evt);
            }
        });
        jPanel1.add(inputApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 420, 30));

        inputDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDireccionActionPerformed(evt);
            }
        });
        jPanel1.add(inputDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 420, 30));

        inputTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(inputTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 420, 30));

        inputCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(inputCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, 420, 30));

        botonEliminarSocio.setBackground(new java.awt.Color(131, 46, 5));
        botonEliminarSocio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonEliminarSocio.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminarSocio.setText("INSERTAR SOCIO");
        botonEliminarSocio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarSocioActionPerformed(evt);
            }
        });
        jPanel1.add(botonEliminarSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 580, 240, 40));

        jLabel1.setText("Apellidos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 70, 20));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 70, 20));

        jLabel3.setText("Correo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 70, 20));

        jLabel4.setText("Telefono");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 70, 20));

        jLabel5.setText("Direccion");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 70, 20));

        btnRegresar1.setBackground(new java.awt.Color(131, 46, 5));
        btnRegresar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegresar1.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar1.setText("REGRESAR");
        btnRegresar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 40));

        botonActualizarSocio.setBackground(new java.awt.Color(131, 46, 5));
        botonActualizarSocio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonActualizarSocio.setForeground(new java.awt.Color(255, 255, 255));
        botonActualizarSocio.setText("ACTUALIZAR");
        botonActualizarSocio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonActualizarSocio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonActualizarSocioMouseClicked(evt);
            }
        });
        botonActualizarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarSocioActionPerformed(evt);
            }
        });
        jPanel1.add(botonActualizarSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 570, 120, 40));

        botonEliminarSocio1.setBackground(new java.awt.Color(131, 46, 5));
        botonEliminarSocio1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonEliminarSocio1.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminarSocio1.setText("ELIMINAR");
        botonEliminarSocio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminarSocio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarSocio1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonEliminarSocio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 570, 110, 40));

        jPanel2.setForeground(new java.awt.Color(60, 63, 65));
        jPanel2.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel2.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaSocios1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id_socio", "Nombre", "Apellidos", "Direccion", "Telefono", "Correo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaSocios1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 570, 340));

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 1, 28)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PANEL DE CONTROL DE SOCIOS");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 440, 40));

        inputNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombre1ActionPerformed(evt);
            }
        });
        jPanel2.add(inputNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 420, 30));

        jTextPane2.setEditable(false);
        jTextPane2.setBackground(new java.awt.Color(0, 0, 0));
        jTextPane2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextPane2.setText("Lista de todos los socios");
        jTextPane2.setToolTipText("");
        jTextPane2.setCaretColor(new java.awt.Color(0, 0, 0));
        jScrollPane5.setViewportView(jTextPane2);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 570, 40));

        inputApellidos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputApellidos1ActionPerformed(evt);
            }
        });
        jPanel2.add(inputApellidos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 420, 30));

        inputDireccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDireccion1ActionPerformed(evt);
            }
        });
        jPanel2.add(inputDireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 420, 30));

        inputTelefono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTelefono1ActionPerformed(evt);
            }
        });
        jPanel2.add(inputTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 420, 30));

        inputCorreo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCorreo1ActionPerformed(evt);
            }
        });
        jPanel2.add(inputCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, 420, 30));

        botonEliminarSocio2.setBackground(new java.awt.Color(131, 46, 5));
        botonEliminarSocio2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonEliminarSocio2.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminarSocio2.setText("INSERTAR SOCIO");
        botonEliminarSocio2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminarSocio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarSocio2ActionPerformed(evt);
            }
        });
        jPanel2.add(botonEliminarSocio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 580, 240, 40));

        jLabel6.setText("Apellidos");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 70, 20));

        jLabel9.setText("Nombre");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 70, 20));

        jLabel10.setText("Correo");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 70, 20));

        jLabel11.setText("Telefono");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 70, 20));

        jLabel12.setText("Direccion");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 70, 20));

        btnRegresar2.setBackground(new java.awt.Color(131, 46, 5));
        btnRegresar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegresar2.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar2.setText("REGRESAR");
        btnRegresar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegresar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 40));

        botonActualizarSocio1.setBackground(new java.awt.Color(131, 46, 5));
        botonActualizarSocio1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonActualizarSocio1.setForeground(new java.awt.Color(255, 255, 255));
        botonActualizarSocio1.setText("ACTUALIZAR");
        botonActualizarSocio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonActualizarSocio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonActualizarSocio1MouseClicked(evt);
            }
        });
        botonActualizarSocio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarSocio1ActionPerformed(evt);
            }
        });
        jPanel2.add(botonActualizarSocio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 570, 120, 40));

        botonEliminarSocio3.setBackground(new java.awt.Color(131, 46, 5));
        botonEliminarSocio3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonEliminarSocio3.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminarSocio3.setText("ELIMINAR");
        botonEliminarSocio3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminarSocio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarSocio3ActionPerformed(evt);
            }
        });
        jPanel2.add(botonEliminarSocio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 570, 110, 40));

        inputIdSocio.setEditable(false);
        inputIdSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdSocioActionPerformed(evt);
            }
        });
        jPanel2.add(inputIdSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 420, 30));

        jLabel13.setText("Id Socio");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 70, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreActionPerformed

    private void inputApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputApellidosActionPerformed

    private void inputDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDireccionActionPerformed

    private void inputTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTelefonoActionPerformed

    private void inputCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCorreoActionPerformed

    private void botonEliminarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarSocioActionPerformed
        // TODO add your handling code here:
        InsertarSocio abrir = new InsertarSocio();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonEliminarSocioActionPerformed

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        // TODO add your handling code here:
        VentanaAdministradorPresentacion abrir = new VentanaAdministradorPresentacion();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    private void botonActualizarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarSocioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_botonActualizarSocioActionPerformed

    private void botonActualizarSocioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonActualizarSocioMouseClicked
        // TODO add your handling code here:
        if (inputIdSocio.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Seleccione un elemento de la tabla", "Error al actualizar", JOptionPane.ERROR_MESSAGE);
        } else {
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Está seguro de querer actualizar este usuario?", "Actualizar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (confirmacion == JOptionPane.YES_OPTION) {
                Socio nuevoSocio = new Socio();

                nuevoSocio.setId_socio(Integer.valueOf(inputIdSocio.getText()));
                nuevoSocio.setNombre(inputNombre.getText());
                nuevoSocio.setApellidos(inputApellidos.getText());
                nuevoSocio.setCorreo(inputCorreo.getText());
                nuevoSocio.setTelefono(inputTelefono.getText());
                nuevoSocio.setDireccion(inputDireccion.getText());

                SocioDaoImpl enlace = new SocioDaoImpl();
                enlace.actualizarSocio(Integer.parseInt(inputIdSocio.getText()), nuevoSocio);
                JOptionPane.showMessageDialog(this, "Socio actualizado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
                cargarSocios();
            } else {
                // Socio ha seleccionado "No" (Cancelar)
                System.out.println("El usuario ha cancelado la actualizacion del rol.");
            }

        }
    }//GEN-LAST:event_botonActualizarSocioMouseClicked

    private void botonEliminarSocio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarSocio1ActionPerformed
        // TODO add your handling code here:
        
        if (inputIdSocio.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Seleccione un elemento de la tabla", "Error al eliminar", JOptionPane.ERROR_MESSAGE);
        } else {
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar este Socio?", "Eliminar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (confirmacion == JOptionPane.YES_OPTION) {
                Socio socioEliminado = new Socio();
                // Socio ha seleccionado "Sí" (Eliminar)
                SocioDaoImpl enlace = new SocioDaoImpl();
                socioEliminado = enlace.eliminarSocio(Integer.parseInt(inputIdSocio.getText()));
                cargarSocios();
                limpiar();

            } else {
                // Socio ha seleccionado "No" (Cancelar)
                System.out.println("El Socio ha cancelado la eliminación del rol.");
            }
        }
    }//GEN-LAST:event_botonEliminarSocio1ActionPerformed

    private void inputNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombre1ActionPerformed

    private void inputApellidos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputApellidos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputApellidos1ActionPerformed

    private void inputDireccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDireccion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDireccion1ActionPerformed

    private void inputTelefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTelefono1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTelefono1ActionPerformed

    private void inputCorreo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCorreo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCorreo1ActionPerformed

    private void botonEliminarSocio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarSocio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarSocio2ActionPerformed

    private void btnRegresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresar2ActionPerformed

    private void botonActualizarSocio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonActualizarSocio1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonActualizarSocio1MouseClicked

    private void botonActualizarSocio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarSocio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonActualizarSocio1ActionPerformed

    private void botonEliminarSocio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarSocio3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarSocio3ActionPerformed

    private void inputIdSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIdSocioActionPerformed

    private void tablaSociosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSociosMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = tablaSocios.getSelectedRow();

        // Verificar que la fila seleccionada sea válida
        if (filaSeleccionada != -1) {
            // Obtener los valores de las celdas de la fila seleccionada
            Object idSocio = tablaSocios.getValueAt(filaSeleccionada, 0);
            Object nombre = tablaSocios.getValueAt(filaSeleccionada, 1);
            Object apellidos = tablaSocios.getValueAt(filaSeleccionada, 2);
            Object direccion = tablaSocios.getValueAt(filaSeleccionada, 3);
            Object telefono = tablaSocios.getValueAt(filaSeleccionada, 4);
            Object correo = tablaSocios.getValueAt(filaSeleccionada, 5);

            // Mostrar los valores en los JTextField correspondientes
            inputIdSocio.setText(idSocio.toString());
            inputNombre.setText(nombre.toString());
            inputApellidos.setText(apellidos.toString());
            inputTelefono.setText(telefono.toString());
            inputDireccion.setText(direccion.toString());
            inputCorreo.setText(correo.toString());
        }
    }//GEN-LAST:event_tablaSociosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(socioPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(socioPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(socioPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(socioPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new socioPresentacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarSocio;
    private javax.swing.JButton botonActualizarSocio1;
    private javax.swing.JButton botonEliminarSocio;
    private javax.swing.JButton botonEliminarSocio1;
    private javax.swing.JButton botonEliminarSocio2;
    private javax.swing.JButton botonEliminarSocio3;
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JButton btnRegresar2;
    private javax.swing.JTextField inputApellidos;
    private javax.swing.JTextField inputApellidos1;
    private javax.swing.JTextField inputCorreo;
    private javax.swing.JTextField inputCorreo1;
    private javax.swing.JTextField inputDireccion;
    private javax.swing.JTextField inputDireccion1;
    private javax.swing.JTextField inputIdSocio;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputNombre1;
    private javax.swing.JTextField inputTelefono;
    private javax.swing.JTextField inputTelefono1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTable tablaSocios;
    private javax.swing.JTable tablaSocios1;
    // End of variables declaration//GEN-END:variables
}
