/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package consultaEstadoCuentaPresentacion;

import cuentasLiquidadasPresentacion.VentanaLiquidarPrestamo;
import loginPresentacion.LoginPresentacion;
import javax.swing.JOptionPane;
import CajaDeAhorro.bd.domain.Cuenta;
import CajaDeAhorro.dao.cuenta.CuentaDaoImpl;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import loginPresentacion.VentanaAdministradorPresentacion;
import loginPresentacion.VentanaCajeroPresentacion;

/**
 *
 * @author Gizelle RM
 */
public class VentanaEstadoCuenta extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEstadoCuenta
     */
    public VentanaEstadoCuenta() {
        initComponents();
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        consultar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar1.setBackground(new java.awt.Color(131, 46, 5));
        btnRegresar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegresar1.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar1.setText("REGRESAR");
        btnRegresar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 27, 130, 40));

        jLabel10.setFont(new java.awt.Font("Eras Demi ITC", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ESTADO DE CUENTA");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 109, -1, 80));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese el número de cuenta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 218, -1, -1));

        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });
        getContentPane().add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 252, 326, -1));

        consultar.setBackground(new java.awt.Color(131, 46, 5));
        consultar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        consultar.setForeground(new java.awt.Color(255, 255, 255));
        consultar.setText("OBTENER ESTADO DE CUENTA");
        consultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });
        getContentPane().add(consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 313, 250, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jonatan Eduardo\\Documents\\GitHub\\Caja-De-Ahorro\\CajaDeAhorroPresentacion\\Img\\fondo2.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        VentanaCajeroPresentacion abrir = new VentanaCajeroPresentacion();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea conocer su estado de cuenta?", "Ventana de confirmación", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            CuentaDaoImpl cuentaDao = new CuentaDaoImpl();

            if (numero.getText().isEmpty() || !numero.getText().matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "El campo de número de cuenta no puede estar vacío y debe ser un número válido", "Error al buscar", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    int numeroCuenta = Integer.parseInt(numero.getText());

                    // Obtener las transacciones asociadas al número de cuenta
                    Cuenta cuentaEncontrada = cuentaDao.obtenerCuentaPorNumero(numeroCuenta);
                    List<Object[]> transacciones = cuentaDao.obtenerTransaccionesPorNumeroCuenta(numeroCuenta);

                    if (cuentaEncontrada != null && !transacciones.isEmpty()) {
                        Document documento = new Document();
                        Font fuente = new Font(Font.FontFamily.HELVETICA, 19, Font.NORMAL);
                        try {
                            String rutaDeExportacion = System.getProperty("user.home") + "/Desktop/EstadoCuenta_" + numeroCuenta + ".pdf";
                            PdfWriter.getInstance(documento, new FileOutputStream(rutaDeExportacion));
                            documento.open();

                            // Agregar título y subtítulo al documento
                            Paragraph titulo = new Paragraph("CAJA DE AHORRO", fuente);
                            Paragraph titulo2 = new Paragraph("S.A DE C.V.", fuente);
                            titulo.setAlignment(Paragraph.ALIGN_CENTER);
                            documento.add(titulo);

                            Paragraph subtitulo = new Paragraph("ESTADO DE CUENTA", fuente);
                            subtitulo.setAlignment(Paragraph.ALIGN_CENTER);
                            documento.add(subtitulo);

                            // Espacio después del título
                            documento.add(new Paragraph(" "));

                            // Añadir la fecha actual
                            String fechaActual = new SimpleDateFormat("dd/MM/yyyy").format(new Date());
                            documento.add(new Paragraph("Fecha: " + fechaActual));

                            // Añadir datos de la cuenta
                            documento.add(new Paragraph("Número de cuenta: " + cuentaEncontrada.getNumeroCuenta()));
                            documento.add(new Paragraph("Tasa de interés: " + cuentaEncontrada.getTasaInteres()));
                            documento.add(new Paragraph("Saldo: " + cuentaEncontrada.getSaldo()));
                            documento.add(new Paragraph("Tipo de cuenta: " + cuentaEncontrada.getTipo()));
                            documento.add(new Paragraph(" ")); // Espacio antes de la tabla

                            // Crear la tabla para mostrar las transacciones
                            PdfPTable tablaTransacciones = new PdfPTable(5); // 5 columnas para los datos de la transacción
                            tablaTransacciones.setWidthPercentage(100);

                            // Encabezados de la tabla
                            tablaTransacciones.addCell("ID Transacción");
                            tablaTransacciones.addCell("ID Operación");
                            tablaTransacciones.addCell("Fecha");
                            tablaTransacciones.addCell("Monto");
                            tablaTransacciones.addCell("Nombre de la operación");

                            // Llenar la tabla con los datos de las transacciones
                            for (Object[] transaccion : transacciones) {
                                tablaTransacciones.addCell(String.valueOf(transaccion[0])); // ID Transacción
                                tablaTransacciones.addCell(String.valueOf(transaccion[1])); // ID Operación
                                tablaTransacciones.addCell(String.valueOf(transaccion[2])); // Fecha
                                tablaTransacciones.addCell(String.valueOf(transaccion[3])); // Monto
                                tablaTransacciones.addCell(String.valueOf(transaccion[4])); // Nombre de la operación
                            }

                            // Agregar la tabla al documento
                            documento.add(tablaTransacciones);

                            documento.close();

                            JOptionPane.showMessageDialog(this, "PDF creado con éxito: " + rutaDeExportacion, "Éxito", JOptionPane.INFORMATION_MESSAGE);
                        } catch (DocumentException | IOException e) {
                            JOptionPane.showMessageDialog(this, "Error al crear el PDF", "Error", JOptionPane.ERROR_MESSAGE);
                            e.printStackTrace();
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "No se encontraron transacciones para el número de cuenta especificado", "Transacciones no encontradas", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Número de cuenta no válido", "Error al buscar", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Consulta cancelada.", "Consulta", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_consultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEstadoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEstadoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEstadoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEstadoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEstadoCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JButton consultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField numero;
    // End of variables declaration//GEN-END:variables
}
