/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package consultarSaldoPresentacion;

import loginPresentacion.LoginPresentacion;
import javax.swing.JOptionPane;
import CajaDeAhorro.bd.domain.Cuenta;
import CajaDeAhorro.dao.cuenta.CuentaDaoImpl;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import cuentasLiquidadasPresentacion.VentanaLiquidarPrestamo;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
import loginPresentacion.VentanaCajeroPresentacion;


/**
 *
 * @author Gizelle RM
 */
public class VentanaConsultaSaldo extends javax.swing.JFrame {

    /**
     * Creates new form VentanaConsultaSaldo
     */
    public VentanaConsultaSaldo() {
        initComponents();
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        setResizable(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        consultar = new javax.swing.JButton();
        numero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnRegresar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Eras Demi ITC", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CONSULTAR SALDO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 73, -1, 80));

        consultar.setBackground(new java.awt.Color(131, 46, 5));
        consultar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        consultar.setForeground(new java.awt.Color(255, 255, 255));
        consultar.setText("CONSULTAR SALDO ");
        consultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });
        getContentPane().add(consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 269, 186, 40));
        getContentPane().add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 229, 326, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese el número de cuenta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        btnRegresar1.setBackground(new java.awt.Color(131, 46, 5));
        btnRegresar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegresar1.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar1.setText("REGRESAR");
        btnRegresar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 32, 130, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jonatan Eduardo\\Documents\\GitHub\\Caja-De-Ahorro\\CajaDeAhorroPresentacion\\Img\\fondo2.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea conocer su saldo actual?", "Ventana de confirmación", JOptionPane.YES_NO_OPTION);
    if (respuesta == JOptionPane.YES_OPTION) {
        // Aquí puedes agregar la lógica para consultar el saldo
        CuentaDaoImpl enlace = new CuentaDaoImpl();
        
        if (numero.getText().isEmpty() || !numero.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "El campo de número de cuenta no puede estar vacío y debe ser un número válido", "Error al buscar", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                // Intentar convertir el texto a un número entero
                int numeroCuenta = Integer.parseInt(numero.getText());
                
                // Obtener la cuenta correspondiente al número de cuenta
                Cuenta cuentaEncontrada = enlace.obtenerCuentaPorNumero(numeroCuenta);
                
                // Si se encontró la cuenta, crear el PDF con sus datos
                if (cuentaEncontrada != null) {
                    Document documento = new Document();
                    Font fuente = new Font(Font.FontFamily.HELVETICA, 19, Font.NORMAL);
                    try {
                        String rutaDeExportacion = System.getProperty("user.home") + "/Desktop/ConsultaSaldo.pdf";
                        PdfWriter.getInstance(documento, new FileOutputStream(rutaDeExportacion));
                        documento.open();

                        // Agregar título y subtítulo al documento
                        Paragraph titulo = new Paragraph("CAJA DE AHORRO", fuente);
                        Paragraph titulo2 = new Paragraph("S.A DE C.V.", fuente);
                        titulo.setAlignment(Paragraph.ALIGN_CENTER);
                        documento.add(titulo);

                        Paragraph subtitulo = new Paragraph("CONSULTA DE SALDO ACTUAL", fuente);
                        subtitulo.setAlignment(Paragraph.ALIGN_CENTER);
                        documento.add(subtitulo);

                        // Espacio después del título
                        documento.add(new Paragraph(" "));

                        // Añadir la fecha actual
                        String fechaActual = new SimpleDateFormat("dd/MM/yyyy").format(new Date());
                        documento.add(new Paragraph("Fecha: " + fechaActual));

                        // Añadir los datos de la cuenta
                        documento.add(new Paragraph("NÚMERO DE CUENTA: " + cuentaEncontrada.getNumeroCuenta()));
                        documento.add(new Paragraph("SALDO: " + cuentaEncontrada.getSaldo()));
                        
                        documento.close();
                        
                        JOptionPane.showMessageDialog(this, "PDF creado con éxito: " + rutaDeExportacion, "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    } catch (DocumentException | IOException e) {
                        JOptionPane.showMessageDialog(this, "Error al crear el PDF", "Error", JOptionPane.ERROR_MESSAGE);
                        e.printStackTrace();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontró ninguna cuenta con el número especificado", "Cuenta no encontrada", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (NumberFormatException e) {
                // Manejar la excepción si no se pudo convertir el texto a un número entero
                JOptionPane.showMessageDialog(this, "Número de cuenta no válido", "Error al buscar", JOptionPane.ERROR_MESSAGE);
            }
        }
    } else {
        // Si el usuario cancela, no hacer nada o mostrar un mensaje opcional
        JOptionPane.showMessageDialog(this, "Consulta cancelada.", "Consulta", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_consultarActionPerformed

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        VentanaCajeroPresentacion abrir = new VentanaCajeroPresentacion();
        abrir.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConsultaSaldo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JButton consultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField numero;
    // End of variables declaration//GEN-END:variables
}
