/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cuentasLiquidadasPresentacion;

import CajaDeAhorro.bd.domain.Cuenta;
import CajaDeAhorro.bd.domain.CuentasLiquidadas;
import CajaDeAhorro.bd.domain.Socio;
import CajaDeAhorro.dao.Socio.SocioDaoImpl;
import CajaDeAhorro.dao.cuenta.CuentaDaoImpl;
import CajaDeAhorro.dao.cuentas_Liquidadas.CuentasLiquidadasDaoImpl;
import CajaDeAhorro.dao.usuario.UsuarioDaoImpl;
import loginPresentacion.*;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jonatan Eduardo
 */
public class VentanaLiquidarPrestamo extends javax.swing.JFrame {

    String tipoBusqueda = "ID Socio";

    /**
     * Creates new form VentanaCajeroPresentacion
     */
    public VentanaLiquidarPrestamo() {
        initComponents();
        setTitle("Ventana para Liquidar Préstamo"); // Añade un título a la ventana
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        setResizable(false); // Hace que el tamaño de la ventana sea fijo
        cargarListaSocios();
        txtIdSocio.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        filtro = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnBuscarCuentas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCuentas = new javax.swing.JTable();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtIdSocio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaSocios = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnBuscar1 = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtNumeroCuenta = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnEliminar2 = new javax.swing.JButton();
        btnBuscarCuentas1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaLiquidez = new javax.swing.JTable();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1250, 680));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Eras Demi ITC", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LIQUIDAR UN PRESTAMO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 560, 50));

        jButton2.setBackground(new java.awt.Color(131, 46, 5));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("REGRESAR");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 40));

        filtro.setBackground(new java.awt.Color(153, 51, 0));
        filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Socio", "Nombre" }));
        filtro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filtro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filtroMouseClicked(evt);
            }
        });
        filtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroActionPerformed(evt);
            }
        });
        jPanel1.add(filtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 30));

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 310, 30));

        btnBuscar.setBackground(new java.awt.Color(131, 46, 5));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("LIQUIDAR PRÉSTAMO");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 300, 50));

        btnBuscarCuentas.setBackground(new java.awt.Color(7, 58, 33));
        btnBuscarCuentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarCuentas.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarCuentas.setText("Obtener cuentas asociadas al socio");
        btnBuscarCuentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCuentasActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 580, 30));

        tablaCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número de Cuenta", "Taza de Interés", "Estatus de la Cuenta", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCuentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaCuentas.setSelectionBackground(new java.awt.Color(153, 51, 0));
        tablaCuentas.getTableHeader().setResizingAllowed(false);
        tablaCuentas.getTableHeader().setReorderingAllowed(false);
        tablaCuentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCuentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCuentas);
        if (tablaCuentas.getColumnModel().getColumnCount() > 0) {
            tablaCuentas.getColumnModel().getColumn(0).setResizable(false);
            tablaCuentas.getColumnModel().getColumn(1).setResizable(false);
            tablaCuentas.getColumnModel().getColumn(2).setResizable(false);
            tablaCuentas.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 580, 160));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 270, -1));
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 270, -1));

        txtIdSocio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(txtIdSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 120, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Saldo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellidos:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 270, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dirección:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Correo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Teléfono:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 270, -1));
        jPanel1.add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 290, 270, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Seleccione:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        tablaSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Socio", "Nombre", "Apellidos", "Dirección", "Teléfono", "Correo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaSocios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaSocios.setSelectionBackground(new java.awt.Color(153, 51, 0));
        tablaSocios.getTableHeader().setResizingAllowed(false);
        tablaSocios.getTableHeader().setReorderingAllowed(false);
        tablaSocios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSociosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaSocios);
        if (tablaSocios.getColumnModel().getColumnCount() > 0) {
            tablaSocios.getColumnModel().getColumn(0).setResizable(false);
            tablaSocios.getColumnModel().getColumn(1).setResizable(false);
            tablaSocios.getColumnModel().getColumn(2).setResizable(false);
            tablaSocios.getColumnModel().getColumn(3).setResizable(false);
            tablaSocios.getColumnModel().getColumn(4).setResizable(false);
            tablaSocios.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 400, 160));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID Socio:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, -1, -1));

        btnBuscar1.setBackground(new java.awt.Color(131, 46, 5));
        btnBuscar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar1.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar1.setText("BUSCAR");
        btnBuscar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 90, 30));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 270, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nombre:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));
        jPanel1.add(txtNumeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 270, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Número de Cuenta: ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, -1, -1));

        btnEliminar2.setBackground(new java.awt.Color(7, 58, 33));
        btnEliminar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar2.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar2.setText("LIstar todos los Socios");
        btnEliminar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 400, 30));

        btnBuscarCuentas1.setBackground(new java.awt.Color(7, 58, 33));
        btnBuscarCuentas1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarCuentas1.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarCuentas1.setText("Obtener cuentas liquidadas del socio");
        btnBuscarCuentas1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCuentas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCuentas1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarCuentas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 580, 30));

        tablaLiquidez.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número de Cuenta", "Tipo de Liquidez", "Folio de Pago"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaLiquidez.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaLiquidez.setSelectionBackground(new java.awt.Color(153, 51, 0));
        tablaLiquidez.getTableHeader().setResizingAllowed(false);
        tablaLiquidez.getTableHeader().setReorderingAllowed(false);
        tablaLiquidez.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaLiquidezMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaLiquidez);
        if (tablaLiquidez.getColumnModel().getColumnCount() > 0) {
            tablaLiquidez.getColumnModel().getColumn(0).setResizable(false);
            tablaLiquidez.getColumnModel().getColumn(1).setResizable(false);
            tablaLiquidez.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, 580, 170));

        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jonatan Eduardo\\Documents\\GitHub\\Caja-De-Ahorro\\CajaDeAhorroPresentacion\\src\\main\\java\\Img\\fondo2.jpg")); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        VentanaCajeroPresentacion abrir = new VentanaCajeroPresentacion();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void filtroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filtroMouseClicked

    }//GEN-LAST:event_filtroMouseClicked

    private void filtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroActionPerformed
        tipoBusqueda = (String) filtro.getSelectedItem();
        System.out.println(tipoBusqueda);
    }//GEN-LAST:event_filtroActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        VentanaConfirmacionPrestamo abrir = new VentanaConfirmacionPrestamo();
        abrir.setVisible(true);
        abrir.setNumeroCuenta(Integer.parseInt(txtNumeroCuenta.getText()));
        abrir.setIdDelSocio(Integer.parseInt(txtIdSocio.getText()));
        this.setVisible(false);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscarCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCuentasActionPerformed
        if (txtIdSocio.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Seleccione un elemento de la tabla", "Error al encontrar cuentas", JOptionPane.ERROR_MESSAGE);
        } else {
            SocioDaoImpl enlace = new SocioDaoImpl();
            java.util.List<Cuenta> listaDeCuentas = enlace.obtenerCuentasPorIdSocio(Integer.parseInt(txtIdSocio.getText()));

            DefaultTableModel modeloTabla = new DefaultTableModel();
            modeloTabla.addColumn("Número de Cuenta");
            modeloTabla.addColumn("Taza de Interés");
            modeloTabla.addColumn("Estatus de la Cuenta");
            modeloTabla.addColumn("Saldo");
            for (Cuenta cuenta : listaDeCuentas) {
                modeloTabla.addRow(new Object[]{cuenta.getNumeroCuenta(), cuenta.getTasaInteres(), cuenta.getEstatusCuenta(), cuenta.getSaldo()});
            }
            tablaCuentas.setModel(modeloTabla);
        }
    }//GEN-LAST:event_btnBuscarCuentasActionPerformed

    private void tablaCuentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCuentasMouseClicked
        int filaSeleccionada = tablaCuentas.getSelectedRow();

        // Verificar que la fila seleccionada sea válida
        if (filaSeleccionada != -1) {
            // Obtener los valores de las celdas de la fila seleccionada
            Object numeroCuenta = tablaCuentas.getValueAt(filaSeleccionada, 0);
            Object saldo = tablaCuentas.getValueAt(filaSeleccionada, 3);

            // Mostrar los valores en los JTextField correspondientes
            txtNumeroCuenta.setText(numeroCuenta.toString());
            txtSaldo.setText(saldo.toString());
        }
    }//GEN-LAST:event_tablaCuentasMouseClicked

    private void tablaSociosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSociosMouseClicked
        // TODO add your handling code here:
        // Obtener el índice de la fila seleccionada
        int filaSeleccionada = tablaSocios.getSelectedRow();

        // Verificar que la fila seleccionada sea válida
        if (filaSeleccionada != -1) {
            // Obtener los valores de las celdas de la fila seleccionada
            Object idSocio = tablaSocios.getValueAt(filaSeleccionada, 0);
            Object nombre = tablaSocios.getValueAt(filaSeleccionada, 1);
            Object apellidos = tablaSocios.getValueAt(filaSeleccionada, 2);
            Object direccion = tablaSocios.getValueAt(filaSeleccionada, 3);
            Object telefono = tablaSocios.getValueAt(filaSeleccionada, 4);
            Object correo = tablaSocios.getValueAt(filaSeleccionada, 5);

            // Mostrar los valores en los JTextField correspondientes
            txtIdSocio.setText(idSocio.toString());
            txtNombre.setText(nombre.toString());
            txtApellidos.setText(apellidos.toString());
            txtDireccion.setText(direccion.toString());
            txtTelefono.setText(telefono.toString());
            txtCorreo.setText(correo.toString());
        }
    }//GEN-LAST:event_tablaSociosMouseClicked

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        // TODO add your handling code here:

        SocioDaoImpl enlace = new SocioDaoImpl();
        DefaultTableModel modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("ID Socio");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Apellidos");
        modeloTabla.addColumn("Dirección");
        modeloTabla.addColumn("Teléfono");
        modeloTabla.addColumn("Correo");

        if (tipoBusqueda.equalsIgnoreCase("Nombre")) {
            java.util.List<Socio> listaDeSocios = enlace.obtenerSociosByNombre(txtBuscar.getText());
            for (Socio socio : listaDeSocios) {
                modeloTabla.addRow(new Object[]{socio.getId_socio(), socio.getNombre(), socio.getApellidos(), socio.getDireccion(), socio.getTelefono(), socio.getCorreo()});
            }
            tablaSocios.setModel(modeloTabla);
        }
        if (tipoBusqueda.equalsIgnoreCase("ID Socio")) {
            if (txtBuscar.getText().isEmpty() || !txtBuscar.getText().matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "El campo de búsqueda no puede estar vacío y no puede ser letra si busca por ID Socio", "Error al buscar", JOptionPane.ERROR_MESSAGE);
            } else {
                Socio socioEncontrado = enlace.obtenerSocioPorId(Integer.parseInt(txtBuscar.getText()));
                if (socioEncontrado != null) {
                    modeloTabla.addRow(new Object[]{socioEncontrado.getId_socio(), socioEncontrado.getNombre(), socioEncontrado.getApellidos(), socioEncontrado.getDireccion(), socioEncontrado.getTelefono(), socioEncontrado.getCorreo()});
                    tablaSocios.setModel(modeloTabla);
                } else {
                    System.out.println("Hay que limpiar la tabla");
                    modeloTabla.addRow(new Object[]{"", "", ""});
                    tablaSocios.setModel(modeloTabla);
                }

            }
        }
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void btnEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar2ActionPerformed
        // TODO add your handling code here:
        cargarListaSocios();
    }//GEN-LAST:event_btnEliminar2ActionPerformed

    private void btnBuscarCuentas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCuentas1ActionPerformed
        // TODO add your handling code here:
        if(txtIdSocio.getText().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(this, "Seleccione un elemento de la tabla", "Error al buscar", JOptionPane.ERROR_MESSAGE);
        }else
        {
            cargarListaCuentasLiquidadas(Integer.parseInt(txtIdSocio.getText()));
        }
    }//GEN-LAST:event_btnBuscarCuentas1ActionPerformed

    private void tablaLiquidezMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaLiquidezMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaLiquidezMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLiquidarPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLiquidarPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLiquidarPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLiquidarPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLiquidarPrestamo().setVisible(true);
            }
        });
    }

    private void SetImageLabel(JLabel Nombrelabel, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(Nombrelabel.getWidth(), Nombrelabel.getHeight(), Image.SCALE_DEFAULT));
        Nombrelabel.setIcon(icon);
        this.repaint();
    }

    public void cargarListaSocios() {
        SocioDaoImpl enlace = new SocioDaoImpl();
        java.util.List<Socio> listaDeSocios = enlace.obtenerTodosLosSocios();

        DefaultTableModel modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("ID Socio");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Apellidos");
        modeloTabla.addColumn("Dirección");
        modeloTabla.addColumn("Teléfono");
        modeloTabla.addColumn("Correo");

        for (Socio socio : listaDeSocios) {
            modeloTabla.addRow(new Object[]{socio.getId_socio(), socio.getNombre(), socio.getApellidos(), socio.getDireccion(), socio.getTelefono(), socio.getCorreo()});
        }
        tablaSocios.setModel(modeloTabla);
    }
    public void cargarListaCuentasLiquidadas(int idSocio)
    {
        CuentasLiquidadasDaoImpl enlace = new CuentasLiquidadasDaoImpl();
        java.util.List<CuentasLiquidadas> listaCuentasLiqui = enlace.obteneCuentasLiquidadasByIdSocio(idSocio);

        DefaultTableModel modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("Número de Cuenta");
        modeloTabla.addColumn("Tipo de Liquidez");
        modeloTabla.addColumn("Folio de Pago");
        
        for (CuentasLiquidadas cuenta : listaCuentasLiqui) {
            modeloTabla.addRow(new Object[]{cuenta.getNumero_cuenta(), cuenta.getTipo_liquidez(), cuenta.getFolio_pago_liquidez()});
        }
        tablaLiquidez.setModel(modeloTabla);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnBuscarCuentas;
    private javax.swing.JButton btnBuscarCuentas1;
    private javax.swing.JButton btnEliminar2;
    private javax.swing.JComboBox<String> filtro;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablaCuentas;
    private javax.swing.JTable tablaLiquidez;
    private javax.swing.JTable tablaSocios;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIdSocio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroCuenta;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
