/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SolicitudPrestamoPresentacion;

/**
 *
 * @author Ramses
 */
import loginPresentacion.VentanaGerentePresentacion;
import CajaDeAhorro.bd.domain.Cuenta;
import CajaDeAhorro.bd.domain.Rol;
import CajaDeAhorro.bd.domain.Socio;
import CajaDeAhorro.bd.domain.SolicitudPrestamo;
import CajaDeAhorro.bd.domain.Usuario;
import CajaDeAhorro.dao.Socio.SocioDaoImpl;
import CajaDeAhorro.dao.cuenta.CuentaDaoImpl;
import CajaDeAhorro.dao.rol.RolDaoImpl;
import CajaDeAhorro.dao.solicitudprestamo.SolicitudPrestamoDaoImpl;
import CajaDeAhorro.dao.usuario.UsuarioDaoImpl;
import java.sql.Timestamp;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ConfigracionSolicitudes extends javax.swing.JFrame {

    Map<String, Integer> MapitaRoles = new HashMap<>();  //variable global

    /**
     * Creates new form ConfigracionSolicitudes
     */
    public ConfigracionSolicitudes() {
        initComponents();
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        setResizable(false); // Hace que el tamaño de la ventana sea fijo
        //cargarListaSolicitudes(); // Cargar los datos al abrir la ventana
    }

    public void cargarListaSolicitudes() {
        SolicitudPrestamoDaoImpl enlace = new SolicitudPrestamoDaoImpl();
        java.util.List<SolicitudPrestamo> listaDeSolicitudes = enlace.obtenerTodasLasSolicitudesPrestamo();

        DefaultTableModel modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("ID solicitud Prestamo");
        modeloTabla.addColumn("ID Socio");
        modeloTabla.addColumn("Monto Prestado");
        modeloTabla.addColumn("Numero de cuenta");
        modeloTabla.addColumn("Tipo de Prestamo");
        modeloTabla.addColumn("Fecha de Solicitud");
        modeloTabla.addColumn("Plazo");
        modeloTabla.addColumn("Numero de montos");
        modeloTabla.addColumn("Descripcion");
        modeloTabla.addColumn("Status");

        for (SolicitudPrestamo solicitud : listaDeSolicitudes) {
            modeloTabla.addRow(new Object[]{solicitud.getIdSolicitudPrestamo(), solicitud.getIdSocio(), solicitud.getMontoPrestado(), solicitud.getnumCuenta(), solicitud.getTipoPrestamo(), solicitud.getFechaSolicitud(), solicitud.getPlazo(), solicitud.getNumMontos(), solicitud.getDescripcion(), solicitud.getEstado()});
        }
        tablaUsuarios.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar3 = new javax.swing.JButton();
        Aprobarbtn1 = new javax.swing.JButton();
        ActulizarPrestamo = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnEliminar2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        idSoli = new javax.swing.JTextField();
        btnBuscar1 = new javax.swing.JButton();
        Aprobarbtn = new javax.swing.JButton();
        btnBuscar2 = new javax.swing.JButton();
        btnBuscar4 = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        idUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        monsoSoli = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        numCuenta = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TipoPrestamo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        FechaSoli = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Plazo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        numMontos = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1dES = new javax.swing.JTextPane();
        btnActualizar1 = new javax.swing.JButton();
        btnBuscar5 = new javax.swing.JButton();
        idSoli1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        btnBuscar3.setBackground(new java.awt.Color(131, 46, 5));
        btnBuscar3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar3.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar3.setText("BUSCAR");
        btnBuscar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar3ActionPerformed(evt);
            }
        });

        Aprobarbtn1.setBackground(new java.awt.Color(131, 46, 5));
        Aprobarbtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Aprobarbtn1.setForeground(new java.awt.Color(255, 255, 255));
        Aprobarbtn1.setText("Aprobar");
        Aprobarbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aprobarbtn1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, "", null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID solicitud Prestamo", "ID Socio", "Monto Prestado", "Numero de cuenta", "Tipo de Prestamo", "Fecha de Solicitud", "Plazo", "Numero de montos", "Descripcion", "Status"
            }
        ));
        tablaUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaUsuarios.setSelectionBackground(new java.awt.Color(153, 51, 0));
        tablaUsuarios.getTableHeader().setResizingAllowed(false);
        tablaUsuarios.getTableHeader().setReorderingAllowed(false);
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaUsuarios);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1161, 480));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminar2.setBackground(new java.awt.Color(7, 58, 33));
        btnEliminar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar2.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar2.setText("LIstar todas las solicitudes");
        btnEliminar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(874, 9, 241, 46));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id Solicitud");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 6, 140, -1));
        jPanel3.add(idSoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 31, 102, -1));

        btnBuscar1.setBackground(new java.awt.Color(131, 46, 5));
        btnBuscar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar1.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar1.setText("Buscar");
        btnBuscar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 28, 108, -1));

        Aprobarbtn.setBackground(new java.awt.Color(131, 46, 5));
        Aprobarbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Aprobarbtn.setForeground(new java.awt.Color(255, 255, 255));
        Aprobarbtn.setText("Aprobar");
        Aprobarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AprobarbtnActionPerformed(evt);
            }
        });
        jPanel3.add(Aprobarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 67, 108, -1));

        btnBuscar2.setBackground(new java.awt.Color(131, 46, 5));
        btnBuscar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar2.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar2.setText("Solicitudes Aprobadas");
        btnBuscar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 85, 192, -1));

        btnBuscar4.setBackground(new java.awt.Color(131, 46, 5));
        btnBuscar4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar4.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar4.setText("Solicitudes en espera");
        btnBuscar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar4ActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 28, 192, -1));

        Cancel.setBackground(new java.awt.Color(131, 46, 5));
        Cancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cancel.setForeground(new java.awt.Color(255, 255, 255));
        Cancel.setText("Cancelar");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel3.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 106, 108, -1));

        back.setBackground(new java.awt.Color(131, 46, 5));
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("REGRESAR");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel3.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1051, 100, 110, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jonatan Eduardo\\Documents\\GitHub\\Caja-De-Ahorro\\CajaDeAhorroPresentacion\\Img\\fondo2.jpg")); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 140));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 482, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jonatan Eduardo\\Documents\\GitHub\\Caja-De-Ahorro\\CajaDeAhorroPresentacion\\Img\\fondo2.jpg")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 1160, 150));

        ActulizarPrestamo.addTab("Solicitudes archivadas", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Id del socio:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 4, -1, -1));

        idUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(idUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 32, 179, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Monto Solicitado");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 72, -1, -1));

        monsoSoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monsoSoliActionPerformed(evt);
            }
        });
        jPanel2.add(monsoSoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 111, 179, 24));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Numero de cuenta");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 153, -1, -1));

        numCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numCuentaActionPerformed(evt);
            }
        });
        jPanel2.add(numCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 187, 179, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tipo de Prestamo");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 233, -1, -1));

        TipoPrestamo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "....", "Prestamo escolar", "Prestamo personal", "Prestamo automotriz", "Prestamo para negocio" }));
        jPanel2.add(TipoPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 267, 179, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha Solicitud");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 307, -1, -1));

        FechaSoli.setToolTipText("(dd/mm/yyyy)");
        FechaSoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaSoliActionPerformed(evt);
            }
        });
        jPanel2.add(FechaSoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 335, 179, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Plazo(meses)");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 366, -1, -1));

        Plazo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "....", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50" }));
        jPanel2.add(Plazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 398, 179, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Numero de montos");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 432, -1, -1));

        numMontos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "....", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50" }));
        numMontos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numMontosActionPerformed(evt);
            }
        });
        jPanel2.add(numMontos, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 460, 179, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Descripción");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 500, -1, -1));

        jScrollPane2.setViewportView(jTextPane1dES);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 528, 179, 79));

        btnActualizar1.setBackground(new java.awt.Color(131, 46, 5));
        btnActualizar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizar1.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar1.setText("ACTUALIZAR");
        btnActualizar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 528, 143, 83));

        btnBuscar5.setBackground(new java.awt.Color(131, 46, 5));
        btnBuscar5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar5.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar5.setText("BUSCAR");
        btnBuscar5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar5ActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(935, 30, 108, -1));

        idSoli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idSoli1ActionPerformed(evt);
            }
        });
        jPanel2.add(idSoli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 33, 102, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Id Solicitud");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 8, 140, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jonatan Eduardo\\Documents\\GitHub\\Caja-De-Ahorro\\CajaDeAhorroPresentacion\\Img\\fondo2.jpg")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 630));

        ActulizarPrestamo.addTab("Actualizar Prestamo", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ActulizarPrestamo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ActulizarPrestamo, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscar3ActionPerformed

    private void Aprobarbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aprobarbtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Aprobarbtn1ActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // Obtener la ID de la solicitud a eliminar
        int idSolicitud = Integer.parseInt(idSoli.getText());

        // Verificar el estado de la solicitud
        SolicitudPrestamoDaoImpl enlace = new SolicitudPrestamoDaoImpl();
        SolicitudPrestamo solicitud = enlace.obtenerSolicitudPrestamoPorId(idSolicitud);

        if (solicitud != null) {
            String estado = solicitud.getEstado();
            if (!estado.equals("Aprobado") && !estado.equals("Aceptado")) {
                // Eliminar la solicitud
                enlace.eliminarSolicitudPrestamo(idSolicitud);
                // Mostrar mensaje de éxito en la interfaz
                JOptionPane.showMessageDialog(this, "Solicitud cancelada correctamente.");
            } else {
                // Mostrar mensaje de error en la interfaz
                JOptionPane.showMessageDialog(this, "No se puede cancelar una solicitud aprobada o aceptada.");
            }
        } else {
            // Mostrar mensaje de error en la interfaz
            JOptionPane.showMessageDialog(this, "No se encontró la solicitud con el ID especificado.");
        }
    }//GEN-LAST:event_CancelActionPerformed

    private void btnBuscar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar4ActionPerformed
        SolicitudPrestamoDaoImpl enlace = new SolicitudPrestamoDaoImpl();
        java.util.List<SolicitudPrestamo> listaDeSolicitudes = enlace.obtenerTodasLasSolicitudesPrestamo();

        DefaultTableModel modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("ID solicitud Prestamo");
        modeloTabla.addColumn("ID Socio");
        modeloTabla.addColumn("Monto Prestado");
        modeloTabla.addColumn("Numero de cuenta");
        modeloTabla.addColumn("Tipo de Prestamo");
        modeloTabla.addColumn("Fecha de Solicitud");
        modeloTabla.addColumn("Plazo");
        modeloTabla.addColumn("Numero de montos");
        modeloTabla.addColumn("Descripcion");
        modeloTabla.addColumn("Status");

        for (SolicitudPrestamo solicitud : listaDeSolicitudes) {
            if (!solicitud.getEstado().equals("Aprobado") && !solicitud.getEstado().equals("Aceptado")) {
                modeloTabla.addRow(new Object[]{solicitud.getIdSolicitudPrestamo(), solicitud.getIdSocio(), solicitud.getMontoPrestado(), solicitud.getnumCuenta(), solicitud.getTipoPrestamo(), solicitud.getFechaSolicitud(), solicitud.getPlazo(), solicitud.getNumMontos(), solicitud.getDescripcion(), solicitud.getEstado()});
            }
        }
        tablaUsuarios.setModel(modeloTabla);
    }//GEN-LAST:event_btnBuscar4ActionPerformed

    private void btnBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar2ActionPerformed
        SolicitudPrestamoDaoImpl enlace = new SolicitudPrestamoDaoImpl();
        java.util.List<SolicitudPrestamo> listaDeSolicitudes = enlace.obtenerTodasLasSolicitudesPrestamo();

        DefaultTableModel modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("ID solicitud Prestamo");
        modeloTabla.addColumn("ID Socio");
        modeloTabla.addColumn("Monto Prestado");
        modeloTabla.addColumn("Numero de cuenta");
        modeloTabla.addColumn("Tipo de Prestamo");
        modeloTabla.addColumn("Fecha de Solicitud");
        modeloTabla.addColumn("Plazo");
        modeloTabla.addColumn("Numero de montos");
        modeloTabla.addColumn("Descripcion");
        modeloTabla.addColumn("Status");

        for (SolicitudPrestamo solicitud : listaDeSolicitudes) {
            if (solicitud.getEstado().equals("Aprobado") || solicitud.getEstado().equals("Aceptado")) {
                modeloTabla.addRow(new Object[]{solicitud.getIdSolicitudPrestamo(), solicitud.getIdSocio(), solicitud.getMontoPrestado(), solicitud.getnumCuenta(), solicitud.getTipoPrestamo(), solicitud.getFechaSolicitud(), solicitud.getPlazo(), solicitud.getNumMontos(), solicitud.getDescripcion(), solicitud.getEstado()});
            }
        }
        tablaUsuarios.setModel(modeloTabla);
    }//GEN-LAST:event_btnBuscar2ActionPerformed

    private void AprobarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AprobarbtnActionPerformed
        int idSolicitud = Integer.parseInt(idSoli.getText());

        SolicitudPrestamoDaoImpl enlace = new SolicitudPrestamoDaoImpl();
        SolicitudPrestamo solicitud = enlace.obtenerSolicitudPrestamoPorId(idSolicitud);

        if (solicitud != null) {
            if (!solicitud.getEstado().equals("Aprobado") && !solicitud.getEstado().equals("Aceptado")) {
                // Actualizar el estado de la solicitud
                enlace.actualizarEstadoSolicitudPrestamo(idSolicitud);
                // Mostrar mensaje de éxito
                JOptionPane.showMessageDialog(this, "La solicitud se aprobó con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // Mostrar mensaje de solicitud ya aprobada
                JOptionPane.showMessageDialog(this, "La solicitud ya fue aprobada anteriormente.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Mostrar mensaje de solicitud no encontrada
            JOptionPane.showMessageDialog(this, "La solicitud con ID " + idSolicitud + " no existe.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AprobarbtnActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed

        SolicitudPrestamoDaoImpl enlace = new SolicitudPrestamoDaoImpl();
        DefaultTableModel modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("ID solicitud Prestamo");
        modeloTabla.addColumn("ID Socio");
        modeloTabla.addColumn("Monto Prestado");
        modeloTabla.addColumn("Numero de cuenta");
        modeloTabla.addColumn("Tipo de Prestamo");
        modeloTabla.addColumn("Fecha de Solicitud");
        modeloTabla.addColumn("Plazo");
        modeloTabla.addColumn("Numero de montos");
        modeloTabla.addColumn("Descripcion");
        modeloTabla.addColumn("Status");

        // Obtener la ID de la solicitud
        int idSolicitud = Integer.parseInt(idSoli.getText());
        SolicitudPrestamo solicitud = enlace.obtenerSolicitudPrestamoPorId(idSolicitud);

        if (solicitud != null) {
            modeloTabla.addRow(new Object[]{solicitud.getIdSolicitudPrestamo(), solicitud.getIdSocio(), solicitud.getMontoPrestado(), solicitud.getnumCuenta(), solicitud.getTipoPrestamo(), solicitud.getFechaSolicitud(), solicitud.getPlazo(), solicitud.getNumMontos(), solicitud.getDescripcion(), solicitud.getEstado()});
            tablaUsuarios.setModel(modeloTabla);
        } else {
            // Mostrar mensaje de error
            JOptionPane.showMessageDialog(this, "La solicitud con ID " + idSolicitud + " no existe.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void btnEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar2ActionPerformed
        tablaUsuarios.removeAll();
        cargarListaSolicitudes(); // Cargar los datos al abrir la ventana
    }//GEN-LAST:event_btnEliminar2ActionPerformed

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        // TODO add your handling code here:
        // Obtener el índice de la fila seleccionada
        int filaSeleccionada = tablaUsuarios.getSelectedRow();

        // Verificar que la fila seleccionada sea válida
        if (filaSeleccionada != -1) {
            // Obtener los valores de las celdas de la fila seleccionada
            Object idsolicitud = tablaUsuarios.getValueAt(filaSeleccionada, 0);
            Object idsocio = tablaUsuarios.getValueAt(filaSeleccionada, 1);
            Object monnto = tablaUsuarios.getValueAt(filaSeleccionada, 2);
            Object numcuenta = tablaUsuarios.getValueAt(filaSeleccionada, 3);
            Object tipoP = tablaUsuarios.getValueAt(filaSeleccionada, 4);
            Object fecha = tablaUsuarios.getValueAt(filaSeleccionada, 5);
            Object plazo = tablaUsuarios.getValueAt(filaSeleccionada, 6);
            Object num_montos = tablaUsuarios.getValueAt(filaSeleccionada, 7);
            Object descrp = tablaUsuarios.getValueAt(filaSeleccionada, 8);
            Object estado = tablaUsuarios.getValueAt(filaSeleccionada, 9);

        }
    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void idUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idUsuarioActionPerformed

    private void monsoSoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monsoSoliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monsoSoliActionPerformed

    private void numCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCuentaActionPerformed

    private void FechaSoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaSoliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaSoliActionPerformed

    private void numMontosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numMontosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numMontosActionPerformed

    private void btnActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar1ActionPerformed
        int idSolicitud = Integer.parseInt(idSoli1.getText().trim()); // Obtener el ID de la solicitud

        // Obtener la solicitud de préstamo actual
        SolicitudPrestamoDaoImpl enlace = new SolicitudPrestamoDaoImpl();
        SolicitudPrestamo solicitud = enlace.obtenerSolicitudPrestamoPorId(idSolicitud);

        // Verificar si la solicitud existe
        if (solicitud == null) {
            JOptionPane.showMessageDialog(this, "La solicitud con ID " + idSolicitud + " no existe.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Actualizar los valores de la solicitud con los nuevos valores de los campos de texto u otros componentes de la interfaz
        solicitud.setMontoPrestado(Double.parseDouble(monsoSoli.getText().trim()));
        solicitud.setnumCuenta(Integer.parseInt(numCuenta.getText().trim()));
        solicitud.setTipoPrestamo((String) TipoPrestamo.getSelectedItem());
        solicitud.setPlazo(Integer.parseInt((String) Plazo.getSelectedItem()));
        solicitud.setNumMontos(Integer.parseInt((String) numMontos.getSelectedItem()));
        solicitud.setDescripcion(jTextPane1dES.getText().trim());

        // Actualizar la solicitud en la base de datos
        enlace.actualizarSolicitudPrestamo(idSolicitud, solicitud);

        // Mostrar mensaje de éxito
        JOptionPane.showMessageDialog(this, "La solicitud se actualizó correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        // Limpiar los campos de texto o reiniciar la interfaz según sea necesario
        limpiarCampos();
    }//GEN-LAST:event_btnActualizar1ActionPerformed

    public void limpiarCampos() {
        idUsuario.setText("");
        monsoSoli.setText("");
        FechaSoli.setText("");
        Plazo.setSelectedIndex(-1);
        jTextPane1dES.setText("");
        numCuenta.setText("");
        TipoPrestamo.setSelectedIndex(-1);
        numMontos.setSelectedIndex(-1);
        idUsuario.setEnabled(true);
        FechaSoli.setEnabled(true);
        idSoli.setText("");
        idSoli1.setText("");

    }
    private void btnBuscar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar5ActionPerformed
        int idSolicitud = Integer.parseInt(idSoli1.getText().trim());
        SolicitudPrestamoDaoImpl enlace = new SolicitudPrestamoDaoImpl();
        SolicitudPrestamo solicitud = enlace.obtenerSolicitudPrestamoPorId(idSolicitud);

        if (solicitud == null) {
            JOptionPane.showMessageDialog(this, "La solicitud con ID " + idSolicitud + " no existe.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Cargar los valores de la solicitud en los campos de texto y comboboxes
            idUsuario.setText(String.valueOf(solicitud.getIdSocio()));
            monsoSoli.setText(String.valueOf(solicitud.getMontoPrestado()));
            numCuenta.setText(String.valueOf(solicitud.getnumCuenta()));
            TipoPrestamo.setSelectedItem(solicitud.getTipoPrestamo());
            FechaSoli.setText(solicitud.getFechaSolicitud().toString());
            Plazo.setSelectedItem(String.valueOf(solicitud.getPlazo()));
            numMontos.setSelectedItem(String.valueOf(solicitud.getNumMontos()));
            jTextPane1dES.setText(solicitud.getDescripcion());

            JOptionPane.showMessageDialog(this, "Solicitud cargada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
        idUsuario.setEnabled(false);
        FechaSoli.setEnabled(false);

    }//GEN-LAST:event_btnBuscar5ActionPerformed

    private void idSoli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idSoli1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idSoli1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       InsertarSolicitudPrestamo abrir = new InsertarSolicitudPrestamo();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigracionSolicitudes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigracionSolicitudes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigracionSolicitudes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigracionSolicitudes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigracionSolicitudes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ActulizarPrestamo;
    private javax.swing.JButton Aprobarbtn;
    private javax.swing.JButton Aprobarbtn1;
    private javax.swing.JButton Cancel;
    private javax.swing.JTextField FechaSoli;
    private javax.swing.JComboBox<String> Plazo;
    private javax.swing.JComboBox<String> TipoPrestamo;
    private javax.swing.JButton back;
    private javax.swing.JButton btnActualizar1;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnBuscar2;
    private javax.swing.JButton btnBuscar3;
    private javax.swing.JButton btnBuscar4;
    private javax.swing.JButton btnBuscar5;
    private javax.swing.JButton btnEliminar2;
    private javax.swing.JTextField idSoli;
    private javax.swing.JTextField idSoli1;
    private javax.swing.JTextField idUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1dES;
    private javax.swing.JTextField monsoSoli;
    private javax.swing.JTextField numCuenta;
    private javax.swing.JComboBox<String> numMontos;
    private javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables
}
