/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SolicitudPrestamoPresentacion;

/**
 *
 * @author Ramses
 */
import SolicitudPrestamoPresentacion.ConfigracionSolicitudes;
import loginPresentacion.VentanaGerentePresentacion;
import CajaDeAhorro.bd.domain.Cuenta;
import CajaDeAhorro.bd.domain.Rol;
import CajaDeAhorro.bd.domain.Socio;
import CajaDeAhorro.bd.domain.SolicitudPrestamo;
import CajaDeAhorro.bd.domain.Usuario;
import CajaDeAhorro.dao.Socio.SocioDaoImpl;
import CajaDeAhorro.dao.cuenta.CuentaDaoImpl;
import CajaDeAhorro.dao.rol.RolDaoImpl;
import CajaDeAhorro.dao.solicitudprestamo.SolicitudPrestamoDaoImpl;
import CajaDeAhorro.dao.usuario.UsuarioDaoImpl;
import java.sql.Timestamp;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class InsertarSolicitudPrestamo extends javax.swing.JFrame {

    Map<String, Integer> MapitaRoles = new HashMap<>();  //variable global

    /**
     * Creates new form InsertarSolicitudPrestamo
     */
    public InsertarSolicitudPrestamo() {
        initComponents();
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        setResizable(false); // Hace que el tamaño de la ventana sea fijo
    }

    public void limpiarCampos() {
        idUsuario.setText("");
        monsoSoli.setText("");
        FechaSoli.setText("");
        Plazo.setSelectedIndex(-1);
        jTextPane1dES.setText("");
        numCuenta.setText("");
        TipoPrestamo.setSelectedIndex(-1);
        numMontos.setSelectedIndex(-1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnSoli = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        monsoSoli = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TipoPrestamo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        FechaSoli = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        numMontos = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1dES = new javax.swing.JTextPane();
        idUsuario = new javax.swing.JTextField();
        btnBuscar1 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnCrearS = new javax.swing.JButton();
        numCuenta = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Plazo = new javax.swing.JComboBox<>();
        btnRegresar2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaSocios = new javax.swing.JTable();
        btnEliminar2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        btnRegresar.setBackground(new java.awt.Color(131, 46, 5));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("REGRESAR");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Elige un rol para el usuario:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tipo de Prestamo");

        btnBuscar.setBackground(new java.awt.Color(131, 46, 5));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar1.setBackground(new java.awt.Color(7, 58, 33));
        btnEliminar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar1.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar1.setText("LIstar todos los usuarios");
        btnEliminar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Usuario", "ID Rol", "Nombre", "Correo", "Contraseña"
            }
        ));
        tablaUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaUsuarios.setSelectionBackground(new java.awt.Color(153, 51, 0));
        tablaUsuarios.getTableHeader().setResizingAllowed(false);
        tablaUsuarios.getTableHeader().setReorderingAllowed(false);
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        btnActualizar.setBackground(new java.awt.Color(131, 46, 5));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 1, 28)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Solicitud de Prestamo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 6, 390, 40));

        btnSoli.setBackground(new java.awt.Color(131, 46, 5));
        btnSoli.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSoli.setForeground(new java.awt.Color(255, 255, 255));
        btnSoli.setText("IR A SOLICITUDES DE PRESTAMO");
        btnSoli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoliActionPerformed(evt);
            }
        });
        getContentPane().add(btnSoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(774, 634, 257, 66));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Id del socio:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 91, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Monto Solicitado");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 159, -1, -1));

        monsoSoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monsoSoliActionPerformed(evt);
            }
        });
        getContentPane().add(monsoSoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 197, 179, 24));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha Solicitud");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 407, -1, -1));

        TipoPrestamo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "....", "Prestamo escolar", "Prestamo personal", "Prestamo automotriz", "Prestamo para negocio" }));
        getContentPane().add(TipoPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 367, 179, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tipo de Prestamo");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 333, -1, -1));

        FechaSoli.setToolTipText("(dd/mm/yyyy)");
        FechaSoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaSoliActionPerformed(evt);
            }
        });
        getContentPane().add(FechaSoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 435, 179, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Plazo(meses)");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 472, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Numero de montos");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 538, -1, -1));

        numMontos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "....", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50" }));
        numMontos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numMontosActionPerformed(evt);
            }
        });
        getContentPane().add(numMontos, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 566, 179, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Descripción");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 606, -1, -1));

        jScrollPane2.setViewportView(jTextPane1dES);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 634, 179, 79));

        idUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(idUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 119, 179, -1));

        btnBuscar1.setBackground(new java.awt.Color(131, 46, 5));
        btnBuscar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar1.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar1.setText("BUSCAR");
        btnBuscar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, 119, 100, 40));

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 128, 402, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Buscar Socio Id:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));

        btnCrearS.setBackground(new java.awt.Color(131, 46, 5));
        btnCrearS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCrearS.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearS.setText("AGREGAR SOLICITUD");
        btnCrearS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearSActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearS, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 634, -1, 66));

        numCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(numCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 273, 179, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Numero de cuenta");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 239, -1, -1));

        Plazo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "....", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50" }));
        getContentPane().add(Plazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 504, 179, -1));

        btnRegresar2.setBackground(new java.awt.Color(131, 46, 5));
        btnRegresar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegresar2.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar2.setText("REGRESAR");
        btnRegresar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 22, 110, 40));

        tablaSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Socio", "Nombre", "Apellidos", "Dirección", "Teléfono", "Correo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaSocios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaSocios.setSelectionBackground(new java.awt.Color(153, 51, 0));
        tablaSocios.getTableHeader().setResizingAllowed(false);
        tablaSocios.getTableHeader().setReorderingAllowed(false);
        tablaSocios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSociosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablaSocios);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 470, 240));

        btnEliminar2.setBackground(new java.awt.Color(7, 58, 33));
        btnEliminar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar2.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar2.setText("LIstar todos los Socios");
        btnEliminar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 470, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jonatan Eduardo\\Documents\\GitHub\\Caja-De-Ahorro\\CajaDeAhorroPresentacion\\Img\\fondo2.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        // ConfiguracionUsuario abrir= new ConfiguracionUsuario();
        // abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnSoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoliActionPerformed
        // TODO add your handling code here:
        ConfigracionSolicitudes abrir = new ConfigracionSolicitudes();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSoliActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        try {
            SocioDaoImpl enlace = new SocioDaoImpl();
            int idSocio = Integer.parseInt(txtBuscar.getText());
            Socio socioEncontrado = enlace.obtenerSocioPorId(idSocio);

            if (socioEncontrado != null) {
                DefaultTableModel modeloTabla = new DefaultTableModel();
                modeloTabla.addColumn("ID Socio");
                modeloTabla.addColumn("Nombre");
                modeloTabla.addColumn("Apellidos");
                modeloTabla.addColumn("Dirección");
                modeloTabla.addColumn("Teléfono");
                modeloTabla.addColumn("Correo");

                modeloTabla.addRow(new Object[]{
                    socioEncontrado.getId_socio(),
                    socioEncontrado.getNombre(),
                    socioEncontrado.getApellidos(),
                    socioEncontrado.getDireccion(),
                    socioEncontrado.getTelefono(),
                    socioEncontrado.getCorreo()
                });
                tablaSocios.setModel(modeloTabla);
            } else {
                // Si no se encuentra el socio, mostrar un mensaje de error o manejarlo según sea necesario
                System.out.println("Socio no encontrado");
            }
        } catch (NumberFormatException e) {
            // Manejar la excepción si el ID no es un número válido
            System.out.println("ID inválido");
        }

    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed

    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked

    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void btnCrearSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearSActionPerformed

        int idUsuarioInt = Integer.parseInt(idUsuario.getText().trim());
        int Monto = Integer.parseInt(monsoSoli.getText().trim());
        String tipoPrestamo = TipoPrestamo.getSelectedItem().toString();
        Timestamp fechaSolicitud = Timestamp.valueOf(FechaSoli.getText().trim());
        int plazoInt = Integer.parseInt(Plazo.getSelectedItem().toString());
        int Numero = Integer.parseInt(numCuenta.getText().trim());
        int Montosnum = Integer.parseInt(numMontos.getSelectedItem().toString());

        if (idUsuario.getText().trim().isEmpty() || monsoSoli.getText().trim().isEmpty() || FechaSoli.getText().trim().isEmpty() || jTextPane1dES.getText().trim().isEmpty() || numCuenta.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe rellenar todos los campos", "Error al insertar", JOptionPane.ERROR_MESSAGE);
        } else {
            SolicitudPrestamo solicitud = new SolicitudPrestamo();
            solicitud.setIdSocio(idUsuarioInt);
            solicitud.setMontoPrestado(Monto);
            solicitud.setnumCuenta(Numero);
            solicitud.setTipoPrestamo(tipoPrestamo);
            solicitud.setFechaSolicitud(fechaSolicitud);
            solicitud.setPlazo(plazoInt);
            solicitud.setNumMontos(Montosnum);
            solicitud.setDescripcion(jTextPane1dES.getText().trim());
            solicitud.setEstado("Pendiente"); // Ajusta según tu necesidad

            SolicitudPrestamoDaoImpl conexionBd = new SolicitudPrestamoDaoImpl();
            conexionBd.crearSolicitudPrestamo(solicitud);
            JOptionPane.showMessageDialog(this, "Solicitud de préstamo insertada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
        }
    }//GEN-LAST:event_btnCrearSActionPerformed

    private void idUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idUsuarioActionPerformed

    private void numMontosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numMontosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numMontosActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void monsoSoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monsoSoliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monsoSoliActionPerformed

    private void numCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCuentaActionPerformed

    private void FechaSoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaSoliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaSoliActionPerformed

    private void btnRegresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar2ActionPerformed
        VentanaGerentePresentacion abrir = new VentanaGerentePresentacion();
        abrir.setVisible(true);
        this.setVisible(false);    }//GEN-LAST:event_btnRegresar2ActionPerformed

    private void tablaSociosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSociosMouseClicked

    }//GEN-LAST:event_tablaSociosMouseClicked

    private void btnEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar2ActionPerformed
        cargarListaSocios();
    }//GEN-LAST:event_btnEliminar2ActionPerformed
    public void cargarListaSocios() {
        SocioDaoImpl enlace = new SocioDaoImpl();
        java.util.List<Socio> listaDeSocios = enlace.obtenerTodosLosSocios();

        DefaultTableModel modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("ID Socio");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Apellidos");
        modeloTabla.addColumn("Dirección");
        modeloTabla.addColumn("Teléfono");
        modeloTabla.addColumn("Correo");

        for (Socio socio : listaDeSocios) {
            modeloTabla.addRow(new Object[]{socio.getId_socio(), socio.getNombre(), socio.getApellidos(), socio.getDireccion(), socio.getTelefono(), socio.getCorreo()});
        }
        tablaSocios.setModel(modeloTabla);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarSolicitudPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarSolicitudPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarSolicitudPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarSolicitudPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarSolicitudPrestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FechaSoli;
    private javax.swing.JComboBox<String> Plazo;
    private javax.swing.JComboBox<String> TipoPrestamo;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnCrearS;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnEliminar2;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRegresar2;
    private javax.swing.JButton btnSoli;
    private javax.swing.JTextField idUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPane1dES;
    private javax.swing.JTextField monsoSoli;
    private javax.swing.JTextField numCuenta;
    private javax.swing.JComboBox<String> numMontos;
    private javax.swing.JTable tablaSocios;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
