/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cuentaPresentacion;
import CajaDeAhorro.bd.domain.Cuenta;
import CajaDeAhorro.dao.cuenta.CuentaDaoImpl;
import java.awt.Image;
import java.awt.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import loginPresentacion.VentanaAdministradorPresentacion;
/**
 *
 * @author Gizelle RM
 */
public class VentanaNuevaCuenta extends javax.swing.JFrame {
String tipoBusqueda = "";
    /**
     * Creates new form VentanaNuevaCuenta
     */
    public VentanaNuevaCuenta() {
        initComponents();
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        setResizable(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filtro = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        numero_cuenta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        saldo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tasa_interes = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnInsertar = new javax.swing.JButton();
        tipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        filtro.setBackground(new java.awt.Color(153, 51, 0));
        filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Rol", "Nombre" }));
        filtro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filtro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filtroMouseClicked(evt);
            }
        });
        filtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 1, 28)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("INSERTAR NUEVA CUENTA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 38, 400, 40));

        btnRegresar.setBackground(new java.awt.Color(131, 46, 5));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("REGRESAR");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 15, 110, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Numero de cuenta");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 131, -1, -1));
        getContentPane().add(numero_cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 153, 290, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tasa de interés");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 202, -1, -1));
        getContentPane().add(saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 302, 290, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Saldo");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 274, -1, -1));
        getContentPane().add(tasa_interes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 234, 290, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tipo");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 342, -1, -1));

        btnInsertar.setBackground(new java.awt.Color(131, 46, 5));
        btnInsertar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsertar.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertar.setText("INSERTAR");
        btnInsertar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 425, 110, 40));

        tipo.setBackground(new java.awt.Color(153, 51, 0));
        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "adulto", "niño" }));
        tipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tipoMouseClicked(evt);
            }
        });
        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });
        getContentPane().add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 364, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jonatan Eduardo\\Documents\\GitHub\\Caja-De-Ahorro\\CajaDeAhorroPresentacion\\Img\\fondo2.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VentanaCuenta abrir= new VentanaCuenta();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        if(numero_cuenta.getText().equalsIgnoreCase("") || tasa_interes.getText().equalsIgnoreCase("")  || saldo.getText().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(this, "Debe rellenar todos los campos", "Error al insertar", JOptionPane.ERROR_MESSAGE);
        }else
        {
            Cuenta nuevacuenta = new Cuenta();
            int numeroCuenta = Integer.parseInt(numero_cuenta.getText());
            int interess = Integer.parseInt(tasa_interes.getText());
            int saldoo = Integer.parseInt(saldo.getText());
            String adult = "adulto";
            String infan = "infante";
            
            
            nuevacuenta.setNumeroCuenta(numeroCuenta);
            nuevacuenta.setTasaInteres(interess);
            nuevacuenta.setEstatusCuenta(1);
            nuevacuenta.setSaldo(saldoo);
            nuevacuenta.setTipo(infan);
            
              if (tipoBusqueda.equalsIgnoreCase("adulto")) {
                   nuevacuenta.setTipo(adult);
              }else{
                    nuevacuenta.setTipo(infan);
               }
          
            

            CuentaDaoImpl conexion = new CuentaDaoImpl();
            conexion.crearCuenta(nuevacuenta);
            JOptionPane.showMessageDialog(this, "Cuenta insertada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            numero_cuenta.setText("");
            tasa_interes.setText("");
            saldo.setText("");
            
        }

    }//GEN-LAST:event_btnInsertarActionPerformed

    private void filtroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filtroMouseClicked

    }//GEN-LAST:event_filtroMouseClicked

    private void filtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroActionPerformed

    private void tipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipoMouseClicked

    }//GEN-LAST:event_tipoMouseClicked

    private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed
        tipoBusqueda = (String) tipo.getSelectedItem();
        System.out.println(tipoBusqueda);
    }//GEN-LAST:event_tipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaNuevaCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaNuevaCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaNuevaCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaNuevaCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaNuevaCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> filtro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField numero_cuenta;
    private javax.swing.JTextField saldo;
    private javax.swing.JTextField tasa_interes;
    private javax.swing.JComboBox<String> tipo;
    // End of variables declaration//GEN-END:variables
}
