/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cuentaPresentacion;

import CajaDeAhorro.bd.domain.Cuenta;
import CajaDeAhorro.dao.cuenta.CuentaDaoImpl;
import java.awt.Image;
import java.awt.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import loginPresentacion.VentanaAdministradorPresentacion;
/**
 *
 * @author Gizelle RM
 */
public class VentanaCuenta extends javax.swing.JFrame {

     String tipoBusqueda = "ID Cuenta";
    public VentanaCuenta() {
        initComponents();
         setLocationRelativeTo(null); // Centra la ventana en la pantalla
        setResizable(false); // Hace que el tamaño de la ventana sea fijo
        cargarlistaCuenta();
        cuenta.setEditable(false);
        
    }

     public void cargarlistaCuenta() {
        CuentaDaoImpl enlace = new CuentaDaoImpl();
        java.util.List<Cuenta> listaDeCuentas = enlace.obtenerTodasLasCuentas();
        System.out.println(listaDeCuentas);

        DefaultTableModel modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("Numcuenta");
        modeloTabla.addColumn("Estatus");
        modeloTabla.addColumn("Saldo");
         modeloTabla.addColumn("TasaInterés");
        for (Cuenta cuenta : listaDeCuentas) {
            modeloTabla.addRow(new Object[]{cuenta.getNumeroCuenta(), cuenta.getEstatusCuenta(), cuenta.getSaldo(), cuenta.getTasaInteres()});
        }
        tablaRoles.setModel(modeloTabla);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRoles = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        Idcuenta = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cuenta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        estatus = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        saldo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        interes = new javax.swing.JTextField();
        Eliminar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Idcuenta1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setBackground(new java.awt.Color(131, 46, 5));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("REGRESAR");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 75, 130, 40));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 1, 28)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PANEL DE CONTROL DE CUENTA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 440, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Inserte el numero de Cuenta:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(7, 58, 33));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("LIstar todas las cuentas");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 249, 430, 30));

        tablaRoles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num cuenta", "Estatus", "Saldo", "Tasa de Interés"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaRoles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaRoles.setSelectionBackground(new java.awt.Color(153, 51, 0));
        tablaRoles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaRolesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tablaRolesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaRolesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaRoles);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 297, 430, 250));

        btnNuevo.setBackground(new java.awt.Color(131, 46, 5));
        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("AGREGAR NUEVO");
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 580, 180, 40));

        Idcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdcuentaActionPerformed(evt);
            }
        });
        getContentPane().add(Idcuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 430, 30));

        btnBuscar.setBackground(new java.awt.Color(131, 46, 5));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 100, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Num cuenta:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, -1, -1));

        cuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 270, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Estatus:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, -1, -1));
        getContentPane().add(estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 270, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Saldo :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Descripcion");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 454, -1, -1));

        saldo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoActionPerformed(evt);
            }
        });
        getContentPane().add(saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 270, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tasa de interés:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, -1, -1));

        interes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(interes, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, 270, -1));

        Eliminar.setBackground(new java.awt.Color(131, 46, 5));
        Eliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar.setText("ELIMINAR");
        Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 560, 100, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Inserte #Cuenta:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, -1, 25));

        Idcuenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Idcuenta1ActionPerformed(evt);
            }
        });
        getContentPane().add(Idcuenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 560, 223, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jonatan Eduardo\\Documents\\GitHub\\Caja-De-Ahorro\\CajaDeAhorroPresentacion\\Img\\fondo2.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VentanaAdministradorPresentacion abrir = new VentanaAdministradorPresentacion();
        abrir.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        tablaRoles.removeAll();
        cargarlistaCuenta();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaRolesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaRolesMouseClicked

        // Obtener el índice de la fila seleccionada
        int filaSeleccionada = tablaRoles.getSelectedRow();

        // Verificar que la fila seleccionada sea válida
        if (filaSeleccionada != -1) {
            // Obtener los valores de las celdas de la fila seleccionada
            Object Numcuenta = tablaRoles.getValueAt(filaSeleccionada, 0);
            Object Estatus = tablaRoles.getValueAt(filaSeleccionada, 1);
            Object Saldo = tablaRoles.getValueAt(filaSeleccionada, 2);
            Object TasaInteres = tablaRoles.getValueAt(filaSeleccionada, 3);

            // Mostrar los valores en los JTextField correspondientes
            cuenta.setText(Numcuenta.toString());
            estatus.setText(Estatus.toString());
            saldo.setText(Saldo.toString());
            interes.setText(TasaInteres.toString());
            
        }
    }//GEN-LAST:event_tablaRolesMouseClicked

    
                                         
                                       

  
        
    private void tablaRolesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaRolesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaRolesMouseExited

    private void tablaRolesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaRolesMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tablaRolesMousePressed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        VentanaNuevaCuenta abrir= new VentanaNuevaCuenta();
        abrir.setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void IdcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdcuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdcuentaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       CuentaDaoImpl enlace = new CuentaDaoImpl();
    
    // Crear un modelo de tabla para mostrar los datos encontrados
    DefaultTableModel modeloTabla = new DefaultTableModel();
    modeloTabla.addColumn("Numcuenta");
    modeloTabla.addColumn("Estatus");
    modeloTabla.addColumn("Saldo");
    modeloTabla.addColumn("TasaInterés");

    // Verificar si el campo de búsqueda está vacío o no es un número
    if (Idcuenta.getText().isEmpty() || !Idcuenta.getText().matches("\\d+")) {
        JOptionPane.showMessageDialog(this, "El campo de búsqueda no puede estar vacío y debe ser un número válido", "Error al buscar", JOptionPane.ERROR_MESSAGE);
    } else {
        try {
            // Intentar convertir el texto a un número entero
            int numeroCuenta = Integer.parseInt(Idcuenta.getText());
            
            // Obtener la cuenta correspondiente al número de cuenta
            Cuenta cuentaEncontrada = enlace.obtenerCuentaPorNumero(numeroCuenta);
            
            // Si se encontró la cuenta, agregar sus datos al modelo de tabla y mostrarlos
            if (cuentaEncontrada != null) {
                modeloTabla.addRow(new Object[]{cuentaEncontrada.getNumeroCuenta(), cuentaEncontrada.getEstatusCuenta(), cuentaEncontrada.getSaldo(), cuentaEncontrada.getTasaInteres()});
                tablaRoles.setModel(modeloTabla);
            } else {
                // Si no se encontró la cuenta, limpiar la tabla (opcional: mostrar un mensaje)
                modeloTabla.addRow(new Object[]{"", "", ""});
                tablaRoles.setModel(modeloTabla);
                JOptionPane.showMessageDialog(this, "No se encontró ninguna cuenta con el número especificado", "Cuenta no encontrada", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NumberFormatException e) {
            // Manejar la excepción si no se pudo convertir el texto a un número entero
            JOptionPane.showMessageDialog(this, "Ingrese un número válido para buscar la cuenta", "Error al buscar", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        CuentaDaoImpl enlace = new CuentaDaoImpl();
    

   
    if (Idcuenta1.getText().isEmpty() || !Idcuenta1.getText().matches("\\d+")) {
        JOptionPane.showMessageDialog(this, "El campo de eliminación no puede estar vacío y debe ser un número válido", "Error al buscar", JOptionPane.ERROR_MESSAGE);
    } else {
        try {
          
            int numeroCuenta = Integer.parseInt(Idcuenta1.getText());
            
            // Obtener la cuenta correspondiente al número de cuenta
              Cuenta cuentaEliminada=  enlace.eliminarCuenta(numeroCuenta);
              //JOptionPane.showMessageDialog(this, "Cuenta eliminada con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            if (cuentaEliminada != null) {
                JOptionPane.showMessageDialog(this, "Cuenta eliminada con éxito, actualice la lista para ver resultados", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró ninguna cuenta con el número especificado", "Cuenta no encontrada", JOptionPane.ERROR_MESSAGE);
            }
           
        } catch (NumberFormatException e) {
            // Manejar la excepción si no se pudo convertir el texto a un número entero
            JOptionPane.showMessageDialog(this, "Ingrese una cuenta válida para eliminar", "Error al buscar", JOptionPane.ERROR_MESSAGE);
        }
    } // TODO add your handling code here:
    }//GEN-LAST:event_EliminarActionPerformed

    private void Idcuenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Idcuenta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Idcuenta1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField Idcuenta;
    private javax.swing.JTextField Idcuenta1;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JTextField cuenta;
    private javax.swing.JTextField estatus;
    private javax.swing.JTextField interes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField saldo;
    private javax.swing.JTable tablaRoles;
    // End of variables declaration//GEN-END:variables
}
